
import React from 'react';
import {
  LayoutDashboard,
  Layers,
  Target,
  TrendingUp,
  Trophy,
  Star,
  Search,
  Settings,
  CreditCard,
  Activity,
  GitCompare,
  Bell,
  Kanban,
  Radio,
  ScanEye,
  Landmark,
  Link2,
  Tv,
  Gauge,
  BarChart3,
  Microscope,
  Fingerprint,
  Users,
  LineChart,
  Share2,
  Briefcase,
  Bot,
  BookHeart,
  ShoppingCart,
  Box,
  Dna,
  Gavel,
  ClipboardCheck,
  Store,
  KeyRound,
  MapPin,
  ScanLine,
  Sparkles,
  HeartPulse,
  Leaf,
  ArrowLeftRight,
  Hammer,
  Brain,
  SearchCheck,
  Swords,
  Megaphone,
  Timer,
  GraduationCap,
  RefreshCw,
  TrendingDown,
  Dices,
  Heart,
  ShieldCheck,
  Thermometer,
  Factory,
  BookOpen,
  Video,
  Crosshair,
  Globe,
  Shield,
  CalendarClock,
  FileCheck,
  LayoutGrid,
  Clock,
  Camera,
  Calculator,
  Package,
  AlertOctagon,
  Shield,
  Sparkles,
  DollarSign,
  BellRing,
  Award,
  Percent,
  Play,
} from 'lucide-react';
import { CardInventory, Sport } from './types.ts';
import { PREPOPULATED_CARDS, PREPOPULATED_SUMMARY, INVENTORY_PLAYERS } from './prepopulatedCards.ts';

export const NAV_ITEMS = [
  { id: 'dashboard', label: 'Dashboard', icon: <LayoutDashboard size={20} />, path: '/' },
  { id: 'collection', label: 'Collection', icon: <Layers size={20} />, path: '/collection' },
  { id: 'builder', label: 'Portfolio Builder', icon: <Kanban size={20} />, path: '/builder' },
  { id: 'deepsearch', label: 'Deep Intelligence', icon: <Search size={20} />, path: '/deep-search' },
  { id: 'audit', label: 'Portfolio Audit', icon: <GitCompare size={20} />, path: '/audit' },
  { id: 'mlbstats', label: 'PressBox Hub', icon: <Trophy size={20} />, path: '/mlb-stats' },
  { id: 'prospects', label: 'Prospect Trends', icon: <TrendingUp size={20} />, path: '/prospects' },
  { id: 'favorites', label: 'Watchlist', icon: <Star size={20} />, path: '/favorites' },
  { id: 'players', label: 'Players', icon: <Search size={20} />, path: '/players' },
  { id: 'teams', label: 'Teams', icon: <Target size={20} />, path: '/teams' },
  { id: 'games', label: 'Games', icon: <Activity size={20} />, path: '/games' },
  { id: 'trends', label: 'Trends', icon: <TrendingUp size={20} />, path: '/trends' },
  { id: 'leaderboard', label: 'Leaderboard', icon: <Trophy size={20} />, path: '/leaderboard' },
  { id: 'compare', label: 'Compare', icon: <GitCompare size={20} />, path: '/compare' },
  { id: 'warroom', label: 'Analyst War Room', icon: <Activity size={20} />, path: '/war-room' },
  { id: 'phaseops', label: 'Phase Ops', icon: <Shield size={20} />, path: '/phase-ops' },
  { id: 'alerts', label: 'Alerts', icon: <Bell size={20} />, path: '/alerts' },
  { id: 'liveimpact', label: 'Live Game Impact', icon: <Radio size={20} />, path: '/live-impact' },
  { id: 'visiongrading', label: 'Vision Grading Lab', icon: <ScanEye size={20} />, path: '/vision-grading' },
  { id: 'fractionalvault', label: 'Fractional Vault', icon: <Landmark size={20} />, path: '/fractional-vault' },
  { id: 'provenance', label: 'Provenance Chain', icon: <Link2 size={20} />, path: '/provenance' },
  { id: 'livebreaks', label: 'Live Breaks', icon: <Tv size={20} />, path: '/live-breaks' },
  // Phases 104-113: Industry-First
  { id: 'live-game-impact-engine', label: 'Game Impact Engine', icon: <Gauge size={20} />, path: '/live-game-impact-engine' },
  { id: 'cross-asset-correlation', label: 'Asset Correlation', icon: <BarChart3 size={20} />, path: '/cross-asset-correlation' },
  { id: 'pre-grade-intelligence', label: 'Pre-Grade AI', icon: <Microscope size={20} />, path: '/pre-grade-intelligence' },
  { id: 'provenance-intelligence', label: 'Provenance Chain', icon: <Fingerprint size={20} />, path: '/provenance-intelligence' },
  { id: 'copy-trading', label: 'Copy Trading', icon: <Users size={20} />, path: '/copy-trading' },
  { id: 'predictive-market-maker', label: 'Market Maker', icon: <LineChart size={20} />, path: '/predictive-market-maker' },
  { id: 'liquidity-twin', label: 'Liquidity Twin', icon: <Zap size={20} />, path: '/liquidity-twin' },
  { id: 'influence-graph', label: 'Influence Graph', icon: <Share2 size={20} />, path: '/influence-graph' },
  { id: 'counterparty-trust-graph', label: 'Trust Graph', icon: <Share2 size={20} />, path: '/counterparty-trust-graph' },
  { id: 'cross-hobby-portfolio', label: 'Cross-Hobby Portfolio', icon: <Briefcase size={20} />, path: '/cross-hobby-portfolio' },
  { id: 'portfolio-scenario-theater', label: 'Scenario Theater', icon: <Activity size={20} />, path: '/portfolio-scenario-theater' },
  { id: 'autonomous-acquisition', label: 'AI Acquisition', icon: <Bot size={20} />, path: '/autonomous-acquisition' },
  { id: 'private-deal-room-agent', label: 'Private Deal Room', icon: <Shield size={20} />, path: '/private-deal-room-agent' },
  { id: 'catalyst-market', label: 'Catalyst Market', icon: <TrendingUp size={20} />, path: '/catalyst-market' },
  { id: 'collection-narrative', label: 'Heritage Story', icon: <BookHeart size={20} />, path: '/collection-narrative' },
  // Phases 114-128: Next-Gen
  { id: 'portfolio-copilot', label: 'AI Copilot', icon: <Bot size={20} />, path: '/portfolio-copilot' },
  { id: 'marketplace-aggregator', label: 'Marketplace', icon: <ShoppingCart size={20} />, path: '/marketplace-aggregator' },
  { id: 'subscription-box', label: 'Sub Box Intel', icon: <Box size={20} />, path: '/subscription-box' },
  { id: 'collector-dna', label: 'Collector DNA', icon: <Dna size={20} />, path: '/collector-dna' },
  { id: 'auction-war-room', label: 'Auction War Room', icon: <Gavel size={20} />, path: '/auction-war-room' },
  { id: 'grading-tracker', label: 'Grading Tracker', icon: <ClipboardCheck size={20} />, path: '/grading-tracker' },
  { id: 'dealer-dashboard', label: 'Dealer Dashboard', icon: <Store size={20} />, path: '/dealer-dashboard' },
  { id: 'fund-manager', label: 'Fund Manager', icon: <Landmark size={20} />, path: '/fund-manager' },
  { id: 'api-licensing', label: 'API & Licensing', icon: <KeyRound size={20} />, path: '/api-licensing' },
  { id: 'card-show-mode', label: 'Card Show Mode', icon: <MapPin size={20} />, path: '/card-show-mode' },
  { id: 'ar-scanner', label: 'AR Scanner', icon: <ScanLine size={20} />, path: '/ar-scanner' },
  { id: 'hype-radar', label: 'Hype Radar', icon: <Radio size={20} />, path: '/hype-radar' },
  { id: 'non-sports', label: 'Non-Sports', icon: <Sparkles size={20} />, path: '/non-sports' },
  { id: 'injury-intel', label: 'Injury Intel', icon: <HeartPulse size={20} />, path: '/injury-intel' },
  { id: 'carbon-score', label: 'Carbon Score', icon: <Leaf size={20} />, path: '/carbon-score' },
  // Phases 129-138: Competitive Differentiators
  { id: 'vault-arbitrage', label: 'Vault Arbitrage', icon: <ArrowLeftRight size={20} />, path: '/vault-arbitrage' },
  { id: 'pressing-roi', label: 'Pressing ROI', icon: <Hammer size={20} />, path: '/pressing-roi' },
  { id: 'behavioral-finance', label: 'Behavioral Finance', icon: <Brain size={20} />, path: '/behavioral-finance' },
  { id: 'comp-forensics', label: 'Comp Forensics', icon: <SearchCheck size={20} />, path: '/comp-forensics' },
  { id: 'tournament-arena', label: 'Tournament Arena', icon: <Swords size={20} />, path: '/tournament-arena' },
  { id: 'influencer-impact', label: 'Influencer Impact', icon: <Megaphone size={20} />, path: '/influencer-impact' },
  { id: 'condition-aging', label: 'Condition Aging', icon: <Timer size={20} />, path: '/condition-aging' },
  { id: 'auth-training', label: 'Auth Academy', icon: <GraduationCap size={20} />, path: '/auth-training' },
  { id: 'inventory-sync', label: 'Inventory Sync', icon: <RefreshCw size={20} />, path: '/inventory-sync' },
  { id: 'rookie-class-index', label: 'Rookie Index', icon: <TrendingDown size={20} />, path: '/rookie-class-index' },
  // Phases 139-148: Production-Grade Expansion
  { id: 'vending-machine', label: 'Pack Simulator', icon: <Dices size={20} />, path: '/vending-machine' },
  { id: 'womens-sports-index', label: "Women's Sports", icon: <Heart size={20} />, path: '/womens-sports-index' },
  { id: 'grading-auditor', label: 'Grading Auditor', icon: <ShieldCheck size={20} />, path: '/grading-auditor' },
  { id: 'smart-storage', label: 'Smart Storage', icon: <Thermometer size={20} />, path: '/smart-storage' },
  { id: 'print-run-intelligence', label: 'Print Run Intel', icon: <Factory size={20} />, path: '/print-run-intelligence' },
  { id: 'youth-onboarding', label: 'New Collector', icon: <BookOpen size={20} />, path: '/youth-onboarding' },
  { id: 'live-break-hub', label: 'Live Break Hub', icon: <Video size={20} />, path: '/live-break-hub' },
  { id: 'price-prediction', label: 'Price Prediction', icon: <Crosshair size={20} />, path: '/price-prediction' },
  { id: 'international-arbitrage', label: 'Intl Arbitrage', icon: <Globe size={20} />, path: '/international-arbitrage' },
  { id: 'blockchain-provenance', label: 'Card Passport', icon: <Shield size={20} />, path: '/blockchain-provenance' },
  // Phases 149-158: Advanced Platform Features
  { id: 'trade-deadline', label: 'Trade Deadline', icon: <CalendarClock size={20} />, path: '/trade-deadline' },
  { id: 'collection-appraiser', label: 'Appraiser', icon: <FileCheck size={20} />, path: '/collection-appraiser' },
  { id: 'set-registry', label: 'Set Registry', icon: <LayoutGrid size={20} />, path: '/set-registry' },
  { id: 'vintage-market', label: 'Vintage Market', icon: <Clock size={20} />, path: '/vintage-market' },
  { id: 'social-trading', label: 'Social Trading', icon: <Users size={20} />, path: '/social-trading' },
  { id: 'listing-optimizer', label: 'Listing Optimizer', icon: <Camera size={20} />, path: '/listing-optimizer' },
  { id: 'tax-calculator', label: 'Tax Calculator', icon: <Calculator size={20} />, path: '/tax-calculator' },
  { id: 'sealed-product', label: 'Sealed Product', icon: <Package size={20} />, path: '/sealed-product' },
  { id: 'error-card', label: 'Error Cards', icon: <AlertOctagon size={20} />, path: '/error-card' },
  { id: 'auction-sniper', label: 'Auction Sniper', icon: <Crosshair size={20} />, path: '/auction-sniper' },
  { id: 'frontier-lab', label: 'Frontier Lab', icon: <Sparkles size={20} />, path: '/frontier-lab' },
  // Phases 159-168: Competitive Feature Suite
  { id: 'real-time-price-engine', label: 'Price Engine', icon: <DollarSign size={20} />, path: '/real-time-price-engine' },
  { id: 'ai-card-scanner', label: 'AI Scanner', icon: <ScanLine size={20} />, path: '/ai-card-scanner' },
  { id: 'cross-platform-arbitrage', label: 'Arbitrage Alerts', icon: <ArrowLeftRight size={20} />, path: '/cross-platform-arbitrage' },
  { id: 'predictive-price-engine', label: 'Price Forecast', icon: <Brain size={20} />, path: '/predictive-price-engine' },
  { id: 'tax-report', label: 'Tax Report', icon: <Calculator size={20} />, path: '/tax-report' },
  { id: 'grade-prediction', label: 'Grade Predict', icon: <Award size={20} />, path: '/grade-prediction' },
  { id: 'smart-notifications', label: 'Smart Alerts', icon: <BellRing size={20} />, path: '/smart-notifications' },
  { id: 'consensus-pricing', label: 'Consensus Price', icon: <Users size={20} />, path: '/consensus-pricing' },
  { id: 'live-break-roi', label: 'Break ROI', icon: <Play size={20} />, path: '/live-break-roi' },
  { id: 'portfolio-benchmark', label: 'Benchmark', icon: <Percent size={20} />, path: '/portfolio-benchmark' },
  { id: 'billing', label: 'Billing', icon: <CreditCard size={20} />, path: '/billing' },
  { id: 'settings', label: 'Settings', icon: <Settings size={20} />, path: '/settings' },
];

export const LEAGUES: readonly string[] = ['MLB', 'MiLB', 'NBA', 'NFL', 'Other'];
export const SPORTS: Sport[] = ['Baseball', 'Basketball', 'Football', 'Hockey', 'Soccer'];

export const GRADING_COMPANIES = ['PSA', 'BGS', 'SGC', 'CSG', 'HGA', 'Other'];

export const MOCK_CARDS: CardInventory[] = PREPOPULATED_CARDS;

const INITIAL_MOCK_PLAYERS = [
  {
    id: '1',
    name: 'Victor Wembanyama',
    team: 'San Antonio Spurs',
    position: 'Center',
    league: 'NBA',
    image: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&q=80&w=300',
    breakoutScore: 94,
    trend: 12,
    intelligenceScore: 98,
    stats: [
      { label: 'PPG', value: '21.4', change: '+3.2' },
      { label: 'RPG', value: '10.6', change: '+1.5' },
      { label: 'BPG', value: '3.6', change: '+0.8' }
    ],
    summary: 'Generational defensive talent with rapidly evolving offensive bag.',
    marketContext: 'Market is pricing in superstardom; current prices reflect long-term potential.'
  },
  {
    id: '2',
    name: 'Tyrese Haliburton',
    team: 'Indiana Pacers',
    position: 'Guard',
    league: 'NBA',
    image: 'https://images.unsplash.com/photo-1519766304817-4f37bda74a26?auto=format&fit=crop&q=80&w=300',
    breakoutScore: 82,
    trend: 5,
    intelligenceScore: 95,
    stats: [
      { label: 'APG', value: '11.7', change: '+2.1' },
      { label: 'PPG', value: '20.1', change: '-1.2' },
      { label: 'TS%', value: '60.5%', change: '+0.5' }
    ],
    summary: 'Elite playmaker whose usage patterns suggest high performance stability.',
    marketContext: 'Strong buy signal for long-term hold collectors.'
  }
];

export const MOCK_PLAYERS = [
  ...INITIAL_MOCK_PLAYERS,
  ...INVENTORY_PLAYERS.filter(p => !INITIAL_MOCK_PLAYERS.some(mp => mp.name.toLowerCase() === p.name.toLowerCase()))
];

export const MOCK_TEAMS = [
  // NBA
  {
    id: 'nba-okc',
    name: 'Oklahoma City Thunder',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/5d/Oklahoma_City_Thunder.svg/1200px-Oklahoma_City_Thunder.svg.png',
    league: 'NBA',
    conference: 'Western',
    division: 'Northwest',
    form: 'hot',
    score: 92,
    offense: 96,
    defense: 94,
    summary: 'Elite young core delivering dominant two-way basketball with league-best net rating.',
    momentum: 'up' as const
  },
  {
    id: 'nba-bos',
    name: 'Boston Celtics',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/8/8f/Boston_Celtics.svg/1200px-Boston_Celtics.svg.png',
    league: 'NBA',
    conference: 'Eastern',
    division: 'Atlantic',
    form: 'hot',
    score: 95,
    offense: 98,
    defense: 92,
    summary: 'Championship-caliber shooting and switching defense making them the team to beat.',
    momentum: 'up' as const
  },
  {
    id: 'nba-den',
    name: 'Denver Nuggets',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/76/Denver_Nuggets.svg/1200px-Denver_Nuggets.svg.png',
    league: 'NBA',
    conference: 'Western',
    division: 'Northwest',
    form: 'variable',
    score: 89,
    offense: 95,
    defense: 88,
    summary: 'Jokic-led offense remains elite but inconsistent defense creates variance.',
    momentum: 'stable' as const
  },
  {
    id: 'nba-min',
    name: 'Minnesota Wolves',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c2/Minnesota_Timberwolves_logo.svg/1200px-Minnesota_Timberwolves_logo.svg.png',
    league: 'NBA',
    conference: 'Western',
    division: 'Northwest',
    form: 'stable',
    score: 91,
    offense: 89,
    defense: 97,
    summary: 'Defensive juggernaut anchored by elite rim protection and perimeter switchability.',
    momentum: 'up' as const
  },
  {
    id: 'nba-lal',
    name: 'LA Lakers',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Los_Angeles_Lakers_logo.svg/1200px-Los_Angeles_Lakers_logo.svg.png',
    league: 'NBA',
    conference: 'Western',
    division: 'Pacific',
    form: 'cold',
    score: 85,
    offense: 91,
    defense: 84,
    summary: 'Star-dependent offense struggling with depth and consistency on the defensive end.',
    momentum: 'down' as const
  },
  {
    id: 'nba-ny',
    name: 'NY Knicks',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/25/New_York_Knicks_logo.svg/1200px-New_York_Knicks_logo.svg.png',
    league: 'NBA',
    conference: 'Eastern',
    division: 'Atlantic',
    form: 'hot',
    score: 88,
    offense: 90,
    defense: 93,
    summary: 'Physical, defense-first identity with improved offensive versatility.',
    momentum: 'up' as const
  },
  // MLB
  {
    id: 'mlb-lad',
    name: 'LA Dodgers',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c7/Los_Angeles_Dodgers_logo.svg/1200px-Los_Angeles_Dodgers_logo.svg.png',
    league: 'MLB',
    conference: 'National',
    division: 'NL West',
    form: 'hot',
    score: 97,
    offense: 99,
    defense: 91,
    summary: 'Loaded roster with historic offensive depth and deep pitching staff.',
    momentum: 'up' as const
  },
  {
    id: 'mlb-atl',
    name: 'Atlanta Braves',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f2/Atlanta_Braves.svg/1200px-Atlanta_Braves.svg.png',
    league: 'MLB',
    conference: 'National',
    division: 'NL East',
    form: 'stable',
    score: 94,
    offense: 96,
    defense: 93,
    summary: 'Consistent powerhouse with elite farm system feeding major league success.',
    momentum: 'stable' as const
  },
  {
    id: 'mlb-bal',
    name: 'Baltimore Orioles',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/75/Baltimore_Orioles_cap.svg/1200px-Baltimore_Orioles_cap.svg.png',
    league: 'MLB',
    conference: 'American',
    division: 'AL East',
    form: 'hot',
    score: 93,
    offense: 94,
    defense: 90,
    summary: 'Young, exciting roster with top-tier prospect pipeline fueling rapid ascent.',
    momentum: 'up' as const
  },
  {
    id: 'mlb-nyy',
    name: 'NY Yankees',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/25/New_York_Yankees_logo.svg/1200px-New_York_Yankees_logo.svg.png',
    league: 'MLB',
    conference: 'American',
    division: 'AL East',
    form: 'variable',
    score: 91,
    offense: 95,
    defense: 88,
    summary: 'Power-heavy lineup with rotation questions creating boom-or-bust variance.',
    momentum: 'stable' as const
  },
  {
    id: 'mlb-tex',
    name: 'Texas Rangers',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Texas_Rangers.svg/1200px-Texas_Rangers.svg.png',
    league: 'MLB',
    conference: 'American',
    division: 'AL West',
    form: 'cold',
    score: 86,
    offense: 92,
    defense: 85,
    summary: 'Defending champions facing regression with pitching injuries and lineup changes.',
    momentum: 'down' as const
  },
  {
    id: 'mlb-phi',
    name: 'Philadelphia Phillies',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0e/Philadelphia_Phillies_Logo.svg/1200px-Philadelphia_Phillies_Logo.svg.png',
    league: 'MLB',
    conference: 'National',
    division: 'NL East',
    form: 'stable',
    score: 90,
    offense: 91,
    defense: 89,
    summary: 'Well-rounded contender with balanced pitching and consistent offensive production.',
    momentum: 'stable' as const
  }
];

export const MOCK_GAMES = [
  {
    id: '1',
    homeTeam: 'NY Knicks',
    awayTeam: 'PHI 76ers',
    homeLogo: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&q=80&w=100',
    awayLogo: 'https://images.unsplash.com/photo-1519766304817-4f37bda74a26?auto=format&fit=crop&q=80&w=100',
    time: '7:30 PM EST',
    impactScore: 88,
    preview: 'High-intensity matchup focusing on interior defensive patterns.',
    keyMatchup: 'Brunson vs. Maxey: A battle of high-speed floor generals.',
    swingFactor: 'Bench depth efficiency in the second quarter.'
  }
];

export const MOCK_INVENTORY_SUMMARY = PREPOPULATED_SUMMARY;

export const MOCK_INVENTORY_ITEMS = PREPOPULATED_CARDS.slice(0, 5).map(card => ({
  id: card.id,
  image: card.image,
  cardName: `${card.year} ${card.manufacturer} ${card.player}`,
  status: card.isGraded ? 'Graded' : 'Raw',
  quantity: 1,
  marketValue: card.currentValue,
  purchasePrice: card.purchasePrice
}));

export const MOCK_ACQUISITION_TARGETS = [
  {
    id: '1',
    name: 'Jackson Holliday',
    team: 'BAL',
    league: 'MiLB',
    focus: 'Prospect',
    marketTrend: 'rising',
    confidence: 92,
    reason: 'Underlying contact metrics suggest elite MLB transition floor.',
    targetPrice: 250,
    image: 'https://img.mlbstatic.com/mlb-photos/person/702616.jpg'
  }
];

