
import React from 'react';
import {
  LayoutDashboard,
  Layers,
  Target,
  TrendingUp,
  Trophy,
  Star,
  Search,
  Settings,
  CreditCard,
  Activity,
  GitCompare,
  Bell,
  Kanban,
  Radio,
  ScanEye,
  Landmark,
  Link2,
  Tv,
  Gauge,
  BarChart3,
  Microscope,
  Fingerprint,
  Users,
  LineChart,
  Share2,
  Briefcase,
  Bot,
  BookHeart,
  ShoppingCart,
  Box,
  Dna,
  Gavel,
  ClipboardCheck,
  Store,
  KeyRound,
  MapPin,
  ScanLine,
  Sparkles,
  HeartPulse,
  Leaf,
  ArrowLeftRight,
  Hammer,
  Brain,
  SearchCheck,
  Swords,
  Megaphone,
  Timer,
  GraduationCap,
  RefreshCw,
  TrendingDown,
  Dices,
  Heart,
  ShieldCheck,
  Thermometer,
  Factory,
  BookOpen,
  Video,
  Crosshair,
  Globe,
  Shield,
  CalendarClock,
  FileCheck,
  LayoutGrid,
  Clock,
  Camera,
  Calculator,
  Package,
  AlertOctagon,
  DollarSign,
  BellRing,
  Award,
  Percent,
  Play,
  Waves,
  CalendarRange,
  ShieldHalf,
  Building2,
  CloudRain,
  Scale,
  History,
  BarChart2,
  Link2 as Link2Icon,
  Compass,
  Zap,
  Eye,
  Mic,
  GitBranch,
  Server,
  Terminal,
  Layers3,
  FlaskConical,
  Workflow,
  Binary,
  Database,
  Radar,
  Newspaper,
  PieChart,
  Puzzle,
  Waypoints,
  Receipt,
  Wand2,
  Lightbulb,
  AlertTriangle,
  Volume2,
  Network,
  PlayCircle,
  MessageSquare,
  Shuffle,
} from 'lucide-react';
import { CardInventory, Sport } from './types.ts';
import { PREPOPULATED_CARDS, PREPOPULATED_SUMMARY, INVENTORY_PLAYERS } from './prepopulatedCards.ts';

export const NAV_ITEMS = [
  { id: 'dashboard', label: 'Dashboard', icon: <LayoutDashboard size={20} />, path: '/' },
  { id: 'collection', label: 'Collection', icon: <Layers size={20} />, path: '/collection' },
  { id: 'builder', label: 'Portfolio Builder', icon: <Kanban size={20} />, path: '/builder' },
  { id: 'deepsearch', label: 'Deep Intelligence', icon: <Search size={20} />, path: '/deep-search' },
  { id: 'audit', label: 'Portfolio Audit', icon: <GitCompare size={20} />, path: '/audit' },
  { id: 'mlbstats', label: 'PressBox Hub', icon: <Trophy size={20} />, path: '/mlb-stats' },
  { id: 'prospects', label: 'Prospect Trends', icon: <TrendingUp size={20} />, path: '/prospects' },
  { id: 'favorites', label: 'Watchlist', icon: <Star size={20} />, path: '/favorites' },
  { id: 'players', label: 'Players', icon: <Search size={20} />, path: '/players' },
  { id: 'teams', label: 'Teams', icon: <Target size={20} />, path: '/teams' },
  { id: 'games', label: 'Games', icon: <Activity size={20} />, path: '/games' },
  { id: 'trends', label: 'Trends', icon: <TrendingUp size={20} />, path: '/trends' },
  { id: 'leaderboard', label: 'Leaderboard', icon: <Trophy size={20} />, path: '/leaderboard' },
  { id: 'compare', label: 'Compare', icon: <GitCompare size={20} />, path: '/compare' },
  { id: 'warroom', label: 'Analyst War Room', icon: <Activity size={20} />, path: '/war-room' },
  { id: 'phaseops', label: 'Phase Ops', icon: <Shield size={20} />, path: '/phase-ops' },
  { id: 'alerts', label: 'Alerts', icon: <Bell size={20} />, path: '/alerts' },
  { id: 'liveimpact', label: 'Live Game Impact', icon: <Radio size={20} />, path: '/live-impact' },
  { id: 'visiongrading', label: 'Vision Grading Lab', icon: <ScanEye size={20} />, path: '/grading-vision-engine' },
  { id: 'fractionalvault', label: 'Fractional Vault', icon: <Landmark size={20} />, path: '/fractional-vault' },
  { id: 'provenance', label: 'Provenance Chain', icon: <Link2 size={20} />, path: '/provenance' },
  { id: 'livebreaks', label: 'Live Breaks', icon: <Tv size={20} />, path: '/live-breaks' },
  // Phases 104-113: Industry-First
  { id: 'live-game-impact-engine', label: 'Game Impact Engine', icon: <Gauge size={20} />, path: '/live-game-impact-engine' },
  { id: 'cross-asset-correlation', label: 'Asset Correlation', icon: <BarChart3 size={20} />, path: '/cross-asset-correlation' },
  { id: 'pre-grade-intelligence', label: 'Pre-Grade AI', icon: <Microscope size={20} />, path: '/pre-grade-intelligence' },
  { id: 'provenance-intelligence', label: 'Provenance Chain', icon: <Fingerprint size={20} />, path: '/provenance-intelligence' },
  { id: 'copy-trading', label: 'Copy Trading', icon: <Users size={20} />, path: '/copy-trading' },
  { id: 'predictive-market-maker', label: 'Market Maker', icon: <LineChart size={20} />, path: '/predictive-market-maker' },
  { id: 'liquidity-twin', label: 'Liquidity Twin', icon: <Zap size={20} />, path: '/liquidity-twin' },
  { id: 'influence-graph', label: 'Influence Graph', icon: <Share2 size={20} />, path: '/influence-graph' },
  { id: 'counterparty-trust-graph', label: 'Trust Graph', icon: <Share2 size={20} />, path: '/counterparty-trust-graph' },
  { id: 'cross-hobby-portfolio', label: 'Cross-Hobby Portfolio', icon: <Briefcase size={20} />, path: '/cross-hobby-portfolio' },
  { id: 'portfolio-scenario-theater', label: 'Scenario Theater', icon: <Activity size={20} />, path: '/portfolio-scenario-theater' },
  { id: 'autonomous-acquisition', label: 'AI Acquisition', icon: <Bot size={20} />, path: '/autonomous-acquisition' },
  { id: 'private-deal-room-agent', label: 'Private Deal Room', icon: <Shield size={20} />, path: '/private-deal-room-agent' },
  { id: 'catalyst-market', label: 'Catalyst Market', icon: <TrendingUp size={20} />, path: '/catalyst-market' },
  { id: 'collection-narrative', label: 'Heritage Story', icon: <BookHeart size={20} />, path: '/collection-narrative' },
  // Phases 114-128: Next-Gen
  { id: 'portfolio-copilot', label: 'AI Copilot', icon: <Bot size={20} />, path: '/portfolio-copilot' },
  { id: 'marketplace-aggregator', label: 'Marketplace', icon: <ShoppingCart size={20} />, path: '/marketplace-aggregator' },
  { id: 'subscription-box', label: 'Sub Box Intel', icon: <Box size={20} />, path: '/subscription-box' },
  { id: 'collector-dna', label: 'Collector DNA', icon: <Dna size={20} />, path: '/collector-dna' },
  { id: 'auction-war-room', label: 'Auction War Room', icon: <Gavel size={20} />, path: '/auction-war-room' },
  { id: 'grading-tracker', label: 'Grading Tracker', icon: <ClipboardCheck size={20} />, path: '/grading-tracker' },
  { id: 'dealer-dashboard', label: 'Dealer Dashboard', icon: <Store size={20} />, path: '/dealer-dashboard' },
  { id: 'fund-manager', label: 'Fund Manager', icon: <Landmark size={20} />, path: '/fund-manager' },
  { id: 'api-licensing', label: 'API & Licensing', icon: <KeyRound size={20} />, path: '/api-licensing' },
  { id: 'card-show-mode', label: 'Card Show Mode', icon: <MapPin size={20} />, path: '/card-show-mode' },
  { id: 'ar-scanner', label: 'AR Scanner', icon: <ScanLine size={20} />, path: '/ar-scanner' },
  { id: 'hype-radar', label: 'Hype Radar', icon: <Radio size={20} />, path: '/hype-radar' },
  { id: 'non-sports', label: 'Non-Sports', icon: <Sparkles size={20} />, path: '/non-sports' },
  { id: 'injury-intel', label: 'Injury Intel', icon: <HeartPulse size={20} />, path: '/injury-intel' },
  { id: 'carbon-score', label: 'Carbon Score', icon: <Leaf size={20} />, path: '/carbon-score' },
  // Phases 129-138: Competitive Differentiators
  { id: 'vault-arbitrage', label: 'Vault Arbitrage', icon: <ArrowLeftRight size={20} />, path: '/vault-arbitrage' },
  { id: 'pressing-roi', label: 'Pressing ROI', icon: <Hammer size={20} />, path: '/pressing-roi' },
  { id: 'behavioral-finance', label: 'Behavioral Finance', icon: <Brain size={20} />, path: '/behavioral-finance' },
  { id: 'comp-forensics', label: 'Comp Forensics', icon: <SearchCheck size={20} />, path: '/comp-forensics' },
  { id: 'tournament-arena', label: 'Tournament Arena', icon: <Swords size={20} />, path: '/tournament-arena' },
  { id: 'influencer-impact', label: 'Influencer Impact', icon: <Megaphone size={20} />, path: '/influencer-impact' },
  { id: 'condition-aging', label: 'Condition Aging', icon: <Timer size={20} />, path: '/condition-aging' },
  { id: 'auth-training', label: 'Auth Academy', icon: <GraduationCap size={20} />, path: '/auth-training' },
  { id: 'inventory-sync', label: 'Inventory Sync', icon: <RefreshCw size={20} />, path: '/inventory-sync' },
  { id: 'rookie-class-index', label: 'Rookie Index', icon: <TrendingDown size={20} />, path: '/rookie-class-index' },
  // Phases 139-148: Production-Grade Expansion
  { id: 'vending-machine', label: 'Pack Simulator', icon: <Dices size={20} />, path: '/vending-machine' },
  { id: 'womens-sports-index', label: "Women's Sports", icon: <Heart size={20} />, path: '/womens-sports-index' },
  { id: 'grading-auditor', label: 'Grading Auditor', icon: <ShieldCheck size={20} />, path: '/grading-auditor' },
  { id: 'smart-storage', label: 'Smart Storage', icon: <Thermometer size={20} />, path: '/smart-storage' },
  { id: 'print-run-intelligence', label: 'Print Run Intel', icon: <Factory size={20} />, path: '/print-run-intelligence' },
  { id: 'youth-onboarding', label: 'New Collector', icon: <BookOpen size={20} />, path: '/youth-onboarding' },
  { id: 'live-break-hub', label: 'Live Break Hub', icon: <Video size={20} />, path: '/live-break-hub' },
  { id: 'price-prediction', label: 'Price Prediction', icon: <Crosshair size={20} />, path: '/price-prediction' },
  { id: 'international-arbitrage', label: 'Intl Arbitrage', icon: <Globe size={20} />, path: '/international-arbitrage' },
  { id: 'blockchain-provenance', label: 'Card Passport', icon: <Shield size={20} />, path: '/blockchain-provenance' },
  // Phases 149-158: Advanced Platform Features
  { id: 'trade-deadline', label: 'Trade Deadline', icon: <CalendarClock size={20} />, path: '/trade-deadline' },
  { id: 'collection-appraiser', label: 'Appraiser', icon: <FileCheck size={20} />, path: '/collection-appraiser' },
  { id: 'set-registry', label: 'Set Registry', icon: <LayoutGrid size={20} />, path: '/set-registry' },
  { id: 'vintage-market', label: 'Vintage Market', icon: <Clock size={20} />, path: '/vintage-market' },
  { id: 'social-trading', label: 'Social Trading', icon: <Users size={20} />, path: '/social-trading' },
  { id: 'listing-optimizer', label: 'Listing Optimizer', icon: <Camera size={20} />, path: '/listing-optimizer' },
  { id: 'tax-calculator', label: 'Tax Calculator', icon: <Calculator size={20} />, path: '/tax-calculator' },
  { id: 'sealed-product', label: 'Sealed Product', icon: <Package size={20} />, path: '/sealed-product' },
  { id: 'error-card', label: 'Error Cards', icon: <AlertOctagon size={20} />, path: '/error-card' },
  { id: 'auction-sniper', label: 'Auction Sniper', icon: <Crosshair size={20} />, path: '/auction-sniper' },
  { id: 'frontier-lab', label: 'Frontier Lab', icon: <Sparkles size={20} />, path: '/frontier-lab' },
  // Phases 159-168: Competitive Feature Suite
  { id: 'real-time-price-engine', label: 'Price Engine', icon: <DollarSign size={20} />, path: '/real-time-price-engine' },
  { id: 'ai-card-scanner', label: 'AI Scanner', icon: <ScanLine size={20} />, path: '/ai-card-scanner' },
  { id: 'cross-platform-arbitrage', label: 'Arbitrage Alerts', icon: <ArrowLeftRight size={20} />, path: '/cross-platform-arbitrage' },
  { id: 'predictive-price-engine', label: 'Price Forecast', icon: <Brain size={20} />, path: '/predictive-price-engine' },
  { id: 'tax-report', label: 'Tax Report', icon: <Calculator size={20} />, path: '/tax-report' },
  { id: 'grade-prediction', label: 'Grade Predict', icon: <Award size={20} />, path: '/grade-prediction' },
  { id: 'smart-notifications', label: 'Smart Alerts', icon: <BellRing size={20} />, path: '/smart-notifications' },
  { id: 'consensus-pricing', label: 'Consensus Price', icon: <Users size={20} />, path: '/consensus-pricing' },
  { id: 'live-break-roi', label: 'Break ROI', icon: <Play size={20} />, path: '/live-break-roi' },
  { id: 'portfolio-benchmark', label: 'Benchmark', icon: <Percent size={20} />, path: '/portfolio-benchmark' },
  { id: 'billing', label: 'Billing', icon: <CreditCard size={20} />, path: '/billing' },
  { id: 'settings', label: 'Settings', icon: <Settings size={20} />, path: '/settings' },
  // v4.0: Multi-Sport League Hubs
  { id: 'nfl-hub', label: 'NFL Hub', icon: <Trophy size={20} />, path: '/nfl-hub' },
  { id: 'nba-hub', label: 'NBA Hub', icon: <Activity size={20} />, path: '/nba-hub' },
  { id: 'nhl-hub', label: 'NHL Hub', icon: <Target size={20} />, path: '/nhl-hub' },
  { id: 'soccer-hub', label: 'Soccer Hub', icon: <Globe size={20} />, path: '/soccer-hub' },
  // v4.0: Multi-Sport & Infrastructure
  { id: 'grading-vision-engine', label: 'Vision Grading', icon: <ScanEye size={20} />, path: '/grading-vision-engine' },
  { id: 'notification-center', label: 'Notifications', icon: <BellRing size={20} />, path: '/notification-center' },
  { id: 'dashboard-builder', label: 'Dashboard Builder', icon: <LayoutGrid size={20} />, path: '/dashboard-builder' },
  { id: 'marketplace-integrations', label: 'Marketplaces', icon: <ShoppingCart size={20} />, path: '/marketplace-integrations' },
  { id: 'insurance-appraisal', label: 'Insurance', icon: <Shield size={20} />, path: '/insurance-appraisal' },
  { id: 'offline-manager', label: 'Offline Mode', icon: <RefreshCw size={20} />, path: '/offline-manager' },
  // v4.0: Industry-First Features
  { id: 'provenance-dna', label: 'Provenance DNA', icon: <Fingerprint size={20} />, path: '/provenance-dna' },
  { id: 'emotional-thermometer', label: 'Emotion Meter', icon: <Thermometer size={20} />, path: '/emotional-thermometer' },
  { id: 'card-weather', label: 'Card Weather', icon: <Activity size={20} />, path: '/card-weather' },
  { id: 'dead-money-detector', label: 'Dead Money', icon: <AlertOctagon size={20} />, path: '/dead-money-detector' },
  { id: 'micro-arbitrage-swarm', label: 'Swarm Network', icon: <Globe size={20} />, path: '/micro-arbitrage-swarm' },
  { id: 'generational-wealth', label: 'Estate Planner', icon: <Landmark size={20} />, path: '/generational-wealth' },
  { id: 'card-aging-lab', label: 'Aging Lab', icon: <Timer size={20} />, path: '/card-aging-lab' },
  { id: 'phantom-backtester', label: 'Backtester', icon: <LineChart size={20} />, path: '/phantom-backtester' },
  { id: 'collector-matchmaker', label: 'Matchmaker', icon: <Users size={20} />, path: '/collector-matchmaker' },
  // v5.0: Next-Gen Investment Intelligence (Batch 1)
  { id: 'card-genome-sequencer', label: 'Card Genome', icon: <Dna size={20} />, path: '/card-genome-sequencer' },
  { id: 'injury-oracle', label: 'Injury Oracle', icon: <HeartPulse size={20} />, path: '/injury-oracle' },
  { id: 'cross-asset-correlation', label: 'Cross-Asset', icon: <ArrowLeftRight size={20} />, path: '/cross-asset-correlation' },
  { id: 'collector-social-graph', label: 'Social Graph', icon: <Share2 size={20} />, path: '/collector-social-graph' },
  { id: 'restoration-simulator', label: 'Restoration Sim', icon: <Hammer size={20} />, path: '/restoration-simulator' },
  { id: 'market-maker-arena', label: 'Bot Arena', icon: <Bot size={20} />, path: '/market-maker-arena' },
  { id: 'fractional-vault', label: 'Fractional Vault', icon: <Landmark size={20} />, path: '/fractional-vault' },
  { id: 'portfolio-stress-tester', label: 'Stress Tester', icon: <Gauge size={20} />, path: '/portfolio-stress-tester' },
  { id: 'rookie-pipeline-scanner', label: 'Prospect Pipeline', icon: <SearchCheck size={20} />, path: '/rookie-pipeline-scanner' },
  { id: 'forensics-lab', label: 'Forensics Lab', icon: <Fingerprint size={20} />, path: '/forensics-lab' },
  // v5.0: Next-Gen Investment Intelligence (Batch 2)
  { id: 'card-decay-predictor', label: 'Decay Predictor', icon: <Thermometer size={20} />, path: '/card-decay-predictor' },
  { id: 'narrative-arc-engine', label: 'Narrative Arcs', icon: <BookOpen size={20} />, path: '/narrative-arc-engine' },
  { id: 'liquidity-depth-scanner', label: 'Liquidity Scanner', icon: <BarChart3 size={20} />, path: '/liquidity-depth-scanner' },
  { id: 'contagion-mapper', label: 'Contagion Map', icon: <Crosshair size={20} />, path: '/contagion-mapper' },
  { id: 'grail-index-constructor', label: 'Grail Index', icon: <LineChart size={20} />, path: '/grail-index-constructor' },
  { id: 'print-run-decoder', label: 'Print Run Decoder', icon: <Calculator size={20} />, path: '/print-run-decoder' },
  { id: 'temporal-arbitrage-radar', label: 'Time Arbitrage', icon: <Clock size={20} />, path: '/temporal-arbitrage-radar' },
  { id: 'collection-dna-mixer', label: 'DNA Mixer', icon: <Dices size={20} />, path: '/collection-dna-mixer' },
  { id: 'card-yield-farming', label: 'Yield Farming', icon: <Leaf size={20} />, path: '/card-yield-farming' },
  { id: 'chaos-theory-simulator', label: 'Chaos Theory', icon: <Sparkles size={20} />, path: '/chaos-theory-simulator' },
  // v5.1: Beyond-Competition Intelligence (Batch 3)
  { id: 'sentiment-volatility-index', label: 'Sentiment Vol', icon: <Waves size={20} />, path: '/sentiment-volatility-index' },
  { id: 'micro-season-capitalizer', label: 'Micro-Seasons', icon: <CalendarRange size={20} />, path: '/micro-season-capitalizer' },
  { id: 'collection-hedge-constructor', label: 'Hedge Builder', icon: <ShieldHalf size={20} />, path: '/collection-hedge-constructor' },
  { id: 'generational-wealth-planner', label: 'Wealth Planner', icon: <Building2 size={20} />, path: '/generational-wealth-planner' },
  { id: 'card-climate-risk-mapper', label: 'Climate Risk', icon: <CloudRain size={20} />, path: '/card-climate-risk-mapper' },
  { id: 'rule-change-impact-modeler', label: 'Rule Changes', icon: <Scale size={20} />, path: '/rule-change-impact-modeler' },
  { id: 'nostalgia-predictor', label: 'Nostalgia', icon: <History size={20} />, path: '/nostalgia-predictor' },
  { id: 'synthetic-card-index', label: 'Card Indices', icon: <BarChart2 size={20} />, path: '/synthetic-card-index' },
  { id: 'provenance-chain-verifier', label: 'Provenance', icon: <Link2Icon size={20} />, path: '/provenance-chain-verifier' },
  { id: 'market-regime-detector', label: 'Market Regime', icon: <Compass size={20} />, path: '/market-regime-detector' },
  // v6.0: Industry-Absent Innovation Suite
  { id: 'injury-shockwave', label: 'Injury Shockwave', icon: <Zap size={20} />, path: '/injury-shockwave' },
  { id: 'ar-vault-walkthrough', label: 'AR Vault', icon: <Eye size={20} />, path: '/ar-vault-walkthrough' },
  { id: 'hof-probability', label: 'HOF Probability', icon: <Award size={20} />, path: '/hof-probability' },
  { id: 'market-microstructure', label: 'Microstructure', icon: <BarChart3 size={20} />, path: '/market-microstructure' },
  { id: 'iot-condition-guardian', label: 'IoT Guardian', icon: <Thermometer size={20} />, path: '/iot-condition-guardian' },
  { id: 'fractional-syndicate', label: 'Syndicates', icon: <Users size={20} />, path: '/fractional-syndicate' },
  { id: 'voice-card-show', label: 'Show Companion', icon: <Mic size={20} />, path: '/voice-card-show' },
  { id: 'narrative-alpha', label: 'Narrative Alpha', icon: <BookOpen size={20} />, path: '/narrative-alpha' },
  { id: 'counterfactual-value', label: 'Counterfactual', icon: <GitBranch size={20} />, path: '/counterfactual-value' },
  { id: 'biometric-trading-guard', label: 'Biometric Guard', icon: <HeartPulse size={20} />, path: '/biometric-trading-guard' },
  // Advanced Trading & Analysis — Wired
  { id: 'draft-war-room', label: 'Draft War Room', icon: <Swords size={20} />, path: '/draft-war-room' },
  // Institutional & Operations
  { id: 'api-platform', label: 'API Platform', icon: <Server size={20} />, path: '/api-platform' },
  { id: 'compliance-center', label: 'Compliance', icon: <ShieldCheck size={20} />, path: '/compliance-center' },
  { id: 'data-consolidation', label: 'Data Hub', icon: <Database size={20} />, path: '/data-consolidation' },
  { id: 'msi-terminal', label: 'MSI Terminal', icon: <Terminal size={20} />, path: '/msi-terminal' },
  { id: 'vault-security', label: 'Vault Security', icon: <Shield size={20} />, path: '/vault-security' },
  // Trading & Marketplace
  { id: 'deal-room', label: 'Deal Room', icon: <Briefcase size={20} />, path: '/deal-room' },
  { id: 'derivatives-desk', label: 'Derivatives Desk', icon: <Binary size={20} />, path: '/derivatives-desk' },
  { id: 'consignment-router', label: 'Consignment Router', icon: <Workflow size={20} />, path: '/consignment-router' },
  { id: 'p2p-marketplace', label: 'P2P Marketplace', icon: <Users size={20} />, path: '/p2p-marketplace' },
  { id: 'transaction-wire', label: 'Transaction Wire', icon: <Receipt size={20} />, path: '/transaction-wire' },
  // Analytics & Intelligence
  { id: 'card-dna', label: 'Card DNA', icon: <Dna size={20} />, path: '/card-dna' },
  { id: 'collection-genome', label: 'Collection Genome', icon: <Puzzle size={20} />, path: '/collection-genome' },
  { id: 'error-card-intel', label: 'Error Card Intel', icon: <AlertOctagon size={20} />, path: '/error-card-intel' },
  { id: 'hof-tracker', label: 'HOF Tracker', icon: <Award size={20} />, path: '/hof-tracker' },
  { id: 'market-indices', label: 'Market Indices', icon: <PieChart size={20} />, path: '/market-indices' },
  { id: 'player-trajectory', label: 'Player Trajectory', icon: <Waypoints size={20} />, path: '/player-trajectory' },
  { id: 'portfolio-attribution', label: 'Attribution', icon: <BarChart3 size={20} />, path: '/portfolio-attribution' },
  { id: 'quant-workbench', label: 'Quant Workbench', icon: <FlaskConical size={20} />, path: '/quant-workbench' },
  { id: 'research-reports', label: 'Research Reports', icon: <Newspaper size={20} />, path: '/research-reports' },
  { id: 'sentiment-radar', label: 'Sentiment Radar', icon: <Radar size={20} />, path: '/sentiment-radar' },
  { id: 'wax-intelligence', label: 'Wax Intel', icon: <Lightbulb size={20} />, path: '/wax-intelligence' },
  { id: 'weather-impact', label: 'Weather Impact', icon: <CloudRain size={20} />, path: '/weather-impact' },
  // Portfolio & Financial
  { id: 'estate-planning', label: 'Estate Planning', icon: <Landmark size={20} />, path: '/estate-planning' },
  { id: 'rebalancer', label: 'Rebalancer', icon: <RefreshCw size={20} />, path: '/rebalancer' },
  { id: 'grading-arbitrage', label: 'Grading Arbitrage', icon: <ArrowLeftRight size={20} />, path: '/grading-arbitrage' },
  // Showcase & Labs
  { id: 'ar-showcase', label: 'AR Showcase', icon: <Eye size={20} />, path: '/ar-showcase' },
  { id: 'inventory', label: 'Inventory', icon: <Layers3 size={20} />, path: '/inventory' },
  // Interactive Demo Flow
  { id: 'demo-flow', label: 'Demo Flow', icon: <Play size={20} />, path: '/demo-flow' },
  // v6.1: Industry-Absent Innovation — Round 2 (Analytics & Intelligence)
  { id: 'dopamine-cycle-tracker', label: 'Dopamine Tracker', icon: <Brain size={20} />, path: '/dopamine-cycle-tracker' },
  { id: 'hobby-liquidity-crisis', label: 'Liquidity Crisis', icon: <AlertTriangle size={20} />, path: '/hobby-liquidity-crisis' },
  { id: 'memory-index', label: 'Memory Index', icon: <Sparkles size={20} />, path: '/memory-index' },
  { id: 'pop-forecaster', label: 'Pop Forecaster', icon: <TrendingUp size={20} />, path: '/pop-forecaster' },
  // v6.1: Industry-Absent Innovation — Round 2 (Trading & Marketplace)
  { id: 'draft-capital-futures', label: 'Draft Futures', icon: <Target size={20} />, path: '/draft-capital-futures' },
  { id: 'shadow-inventory', label: 'Shadow Inventory', icon: <MapPin size={20} />, path: '/shadow-inventory' },
  // v6.1: Industry-Absent Innovation — Round 2 (Portfolio & Financial)
  { id: 'emotion-journal', label: 'Emotion Journal', icon: <Heart size={20} />, path: '/emotion-journal' },
  { id: 'estate-succession', label: 'Estate Succession', icon: <Landmark size={20} />, path: '/estate-succession' },
  // v6.1: Industry-Absent Innovation — Round 2 (Showcase & Labs)
  { id: 'refractor-mapper', label: 'Refractor Mapper', icon: <Eye size={20} />, path: '/refractor-mapper' },
  { id: 'centering-analyzer', label: 'Centering Analyzer', icon: <Crosshair size={20} />, path: '/centering-analyzer' },
  // v7.0: Industry-Absent Innovation — Round 3 (Compliance & Regulation)
  { id: 'regulatory-compliance-radar', label: 'Compliance Radar', icon: <Shield size={20} />, path: '/regulatory-compliance-radar' },
  // v7.0: Industry-Absent Innovation — Round 3 (Authentication & Material Science)
  { id: 'acoustic-authentication', label: 'Acoustic Auth', icon: <Volume2 size={20} />, path: '/acoustic-authentication' },
  { id: 'card-material-spectrometry', label: 'Spectrometry Lab', icon: <Microscope size={20} />, path: '/card-material-spectrometry' },
  // v7.0: Industry-Absent Innovation — Round 3 (Market Intelligence)
  { id: 'dealer-flow-intelligence', label: 'Dealer Flow Intel', icon: <Briefcase size={20} />, path: '/dealer-flow-intelligence' },
  { id: 'psychographic-demand', label: 'Psychographic Demand', icon: <Users size={20} />, path: '/psychographic-demand' },
  { id: 'micro-geographic-demand', label: 'Geo Demand Map', icon: <MapPin size={20} />, path: '/micro-geographic-demand' },
  { id: 'cross-hobby-contagion', label: 'Cross-Hobby Contagion', icon: <Network size={20} />, path: '/cross-hobby-contagion' },
  // v7.0: Industry-Absent Innovation — Round 3 (Trading & Strategy)
  { id: 'venue-health-oracle', label: 'Venue Oracle', icon: <Building2 size={20} />, path: '/venue-health-oracle' },
  { id: 'negotiation-replay', label: 'Negotiation Replay', icon: <PlayCircle size={20} />, path: '/negotiation-replay' },
  { id: 'generational-demand-forecaster', label: 'Gen Forecaster', icon: <Clock size={20} />, path: '/generational-demand-forecaster' },
  // v7.1: Industry-Absent Innovation — Round 4 (Authentication & Grading)
  { id: 'slab-case-forensics', label: 'Slab Forensics', icon: <ScanLine size={20} />, path: '/slab-case-forensics' },
  { id: 'grading-arbitrage', label: 'Grade Arbitrage', icon: <ArrowLeftRight size={20} />, path: '/grading-arbitrage' },
  { id: 'card-aging-clock', label: 'Aging Clock', icon: <Clock size={20} />, path: '/card-aging-clock' },
  // v7.1: Industry-Absent Innovation — Round 4 (Market Intelligence)
  { id: 'price-whisperer', label: 'Price Whisperer', icon: <MessageSquare size={20} />, path: '/price-whisperer' },
  { id: 'sentiment-seismograph', label: 'Sentiment Seismo', icon: <Activity size={20} />, path: '/sentiment-seismograph' },
  { id: 'influencer-quantifier', label: 'Influencer Impact', icon: <Megaphone size={20} />, path: '/influencer-quantifier' },
  { id: 'manipulation-detector', label: 'Manipulation Radar', icon: <AlertTriangle size={20} />, path: '/manipulation-detector' },
  { id: 'contract-valuation', label: 'Contract Value', icon: <FileCheck size={20} />, path: '/contract-valuation' },
  { id: 'draft-night-tracker', label: 'Draft Night Live', icon: <Zap size={20} />, path: '/draft-night-tracker' },
  // v7.1: Industry-Absent Innovation — Round 4 (Trading & Financial)
  { id: 'card-loan-collateral', label: 'Card Collateral', icon: <Landmark size={20} />, path: '/card-loan-collateral' },
  { id: 'consignment-optimizer', label: 'Consignment Opt', icon: <Scale size={20} />, path: '/consignment-optimizer' },
  { id: 'recession-playbook', label: 'Recession Playbook', icon: <BookOpen size={20} />, path: '/recession-playbook' },
  { id: 'peer-lending', label: 'Peer Lending', icon: <ArrowLeftRight size={20} />, path: '/peer-lending' },
  // v7.1: Industry-Absent Innovation — Round 4 (Tools & Experience)
  { id: 'card-show-navigator', label: 'Show Navigator', icon: <MapPin size={20} />, path: '/card-show-navigator' },
  { id: 'wax-ct-scanner', label: 'Wax CT Scanner', icon: <Box size={20} />, path: '/wax-ct-scanner' },
  { id: 'insurance-claims-ai', label: 'Claims AI', icon: <Shield size={20} />, path: '/insurance-claims-ai' },
  { id: 'collection-entropy', label: 'Entropy Score', icon: <Dices size={20} />, path: '/collection-entropy' },
  { id: 'personality-matrix', label: 'Personality Matrix', icon: <Users size={20} />, path: '/personality-matrix' },
  { id: 'photo-studio', label: 'Photo Studio', icon: <Camera size={20} />, path: '/photo-studio' },
  { id: 'vintage-provenance', label: 'Vintage Provenance', icon: <History size={20} />, path: '/vintage-provenance' },
  // Formerly coming-soon features — now live
  { id: 'what-if-simulator', label: 'What-If Simulator', icon: <FlaskConical size={20} />, path: '/what-if-simulator' },
  { id: 'grading-batch-planner', label: 'Grading Planner', icon: <ClipboardCheck size={20} />, path: '/grading-batch-planner' },
  { id: 'ebay-listing-generator', label: 'eBay Listings', icon: <ShoppingCart size={20} />, path: '/ebay-listing-generator' },
  { id: 'wax-break-roi-tracker', label: 'Wax Break ROI', icon: <Box size={20} />, path: '/wax-break-roi-tracker' },
];

export const LEAGUES: readonly string[] = ['MLB', 'MiLB', 'NBA', 'NFL', 'Other'];
export const SPORTS: Sport[] = ['Baseball', 'Basketball', 'Football', 'Hockey', 'Soccer'];

export const GRADING_COMPANIES = ['PSA', 'BGS', 'SGC', 'CSG', 'HGA', 'Other'];

export const MOCK_CARDS: CardInventory[] = PREPOPULATED_CARDS;

const INITIAL_MOCK_PLAYERS = [
  {
    id: '1',
    name: 'Victor Wembanyama',
    team: 'San Antonio Spurs',
    position: 'Center',
    league: 'NBA',
    image: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&q=80&w=300',
    breakoutScore: 94,
    trend: 12,
    intelligenceScore: 98,
    stats: [
      { label: 'PPG', value: '21.4', change: '+3.2' },
      { label: 'RPG', value: '10.6', change: '+1.5' },
      { label: 'BPG', value: '3.6', change: '+0.8' }
    ],
    summary: 'Generational defensive talent with rapidly evolving offensive bag.',
    marketContext: 'Market is pricing in superstardom; current prices reflect long-term potential.'
  },
  {
    id: '2',
    name: 'Tyrese Haliburton',
    team: 'Indiana Pacers',
    position: 'Guard',
    league: 'NBA',
    image: 'https://images.unsplash.com/photo-1519766304817-4f37bda74a26?auto=format&fit=crop&q=80&w=300',
    breakoutScore: 82,
    trend: 5,
    intelligenceScore: 95,
    stats: [
      { label: 'APG', value: '11.7', change: '+2.1' },
      { label: 'PPG', value: '20.1', change: '-1.2' },
      { label: 'TS%', value: '60.5%', change: '+0.5' }
    ],
    summary: 'Elite playmaker whose usage patterns suggest high performance stability.',
    marketContext: 'Strong buy signal for long-term hold collectors.'
  }
];

export const MOCK_PLAYERS = [
  ...INITIAL_MOCK_PLAYERS,
  ...INVENTORY_PLAYERS.filter(p => !INITIAL_MOCK_PLAYERS.some(mp => mp.name.toLowerCase() === p.name.toLowerCase()))
];

export const MOCK_TEAMS = [
  // NBA
  {
    id: 'nba-okc',
    name: 'Oklahoma City Thunder',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/5d/Oklahoma_City_Thunder.svg/1200px-Oklahoma_City_Thunder.svg.png',
    league: 'NBA',
    conference: 'Western',
    division: 'Northwest',
    form: 'hot',
    score: 92,
    offense: 96,
    defense: 94,
    summary: 'Elite young core delivering dominant two-way basketball with league-best net rating.',
    momentum: 'up' as const
  },
  {
    id: 'nba-bos',
    name: 'Boston Celtics',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/8/8f/Boston_Celtics.svg/1200px-Boston_Celtics.svg.png',
    league: 'NBA',
    conference: 'Eastern',
    division: 'Atlantic',
    form: 'hot',
    score: 95,
    offense: 98,
    defense: 92,
    summary: 'Championship-caliber shooting and switching defense making them the team to beat.',
    momentum: 'up' as const
  },
  {
    id: 'nba-den',
    name: 'Denver Nuggets',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/76/Denver_Nuggets.svg/1200px-Denver_Nuggets.svg.png',
    league: 'NBA',
    conference: 'Western',
    division: 'Northwest',
    form: 'variable',
    score: 89,
    offense: 95,
    defense: 88,
    summary: 'Jokic-led offense remains elite but inconsistent defense creates variance.',
    momentum: 'stable' as const
  },
  {
    id: 'nba-min',
    name: 'Minnesota Wolves',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c2/Minnesota_Timberwolves_logo.svg/1200px-Minnesota_Timberwolves_logo.svg.png',
    league: 'NBA',
    conference: 'Western',
    division: 'Northwest',
    form: 'stable',
    score: 91,
    offense: 89,
    defense: 97,
    summary: 'Defensive juggernaut anchored by elite rim protection and perimeter switchability.',
    momentum: 'up' as const
  },
  {
    id: 'nba-lal',
    name: 'LA Lakers',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Los_Angeles_Lakers_logo.svg/1200px-Los_Angeles_Lakers_logo.svg.png',
    league: 'NBA',
    conference: 'Western',
    division: 'Pacific',
    form: 'cold',
    score: 85,
    offense: 91,
    defense: 84,
    summary: 'Star-dependent offense struggling with depth and consistency on the defensive end.',
    momentum: 'down' as const
  },
  {
    id: 'nba-ny',
    name: 'NY Knicks',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/25/New_York_Knicks_logo.svg/1200px-New_York_Knicks_logo.svg.png',
    league: 'NBA',
    conference: 'Eastern',
    division: 'Atlantic',
    form: 'hot',
    score: 88,
    offense: 90,
    defense: 93,
    summary: 'Physical, defense-first identity with improved offensive versatility.',
    momentum: 'up' as const
  },
  // MLB
  {
    id: 'mlb-lad',
    name: 'LA Dodgers',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c7/Los_Angeles_Dodgers_logo.svg/1200px-Los_Angeles_Dodgers_logo.svg.png',
    league: 'MLB',
    conference: 'National',
    division: 'NL West',
    form: 'hot',
    score: 97,
    offense: 99,
    defense: 91,
    summary: 'Loaded roster with historic offensive depth and deep pitching staff.',
    momentum: 'up' as const
  },
  {
    id: 'mlb-atl',
    name: 'Atlanta Braves',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f2/Atlanta_Braves.svg/1200px-Atlanta_Braves.svg.png',
    league: 'MLB',
    conference: 'National',
    division: 'NL East',
    form: 'stable',
    score: 94,
    offense: 96,
    defense: 93,
    summary: 'Consistent powerhouse with elite farm system feeding major league success.',
    momentum: 'stable' as const
  },
  {
    id: 'mlb-bal',
    name: 'Baltimore Orioles',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/75/Baltimore_Orioles_cap.svg/1200px-Baltimore_Orioles_cap.svg.png',
    league: 'MLB',
    conference: 'American',
    division: 'AL East',
    form: 'hot',
    score: 93,
    offense: 94,
    defense: 90,
    summary: 'Young, exciting roster with top-tier prospect pipeline fueling rapid ascent.',
    momentum: 'up' as const
  },
  {
    id: 'mlb-nyy',
    name: 'NY Yankees',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/25/New_York_Yankees_logo.svg/1200px-New_York_Yankees_logo.svg.png',
    league: 'MLB',
    conference: 'American',
    division: 'AL East',
    form: 'variable',
    score: 91,
    offense: 95,
    defense: 88,
    summary: 'Power-heavy lineup with rotation questions creating boom-or-bust variance.',
    momentum: 'stable' as const
  },
  {
    id: 'mlb-tex',
    name: 'Texas Rangers',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Texas_Rangers.svg/1200px-Texas_Rangers.svg.png',
    league: 'MLB',
    conference: 'American',
    division: 'AL West',
    form: 'cold',
    score: 86,
    offense: 92,
    defense: 85,
    summary: 'Defending champions facing regression with pitching injuries and lineup changes.',
    momentum: 'down' as const
  },
  {
    id: 'mlb-phi',
    name: 'Philadelphia Phillies',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0e/Philadelphia_Phillies_Logo.svg/1200px-Philadelphia_Phillies_Logo.svg.png',
    league: 'MLB',
    conference: 'National',
    division: 'NL East',
    form: 'stable',
    score: 90,
    offense: 91,
    defense: 89,
    summary: 'Well-rounded contender with balanced pitching and consistent offensive production.',
    momentum: 'stable' as const
  }
];

export const MOCK_GAMES = [
  {
    id: '1',
    homeTeam: 'NY Knicks',
    awayTeam: 'PHI 76ers',
    homeLogo: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&q=80&w=100',
    awayLogo: 'https://images.unsplash.com/photo-1519766304817-4f37bda74a26?auto=format&fit=crop&q=80&w=100',
    time: '7:30 PM EST',
    impactScore: 88,
    preview: 'High-intensity matchup focusing on interior defensive patterns.',
    keyMatchup: 'Brunson vs. Maxey: A battle of high-speed floor generals.',
    swingFactor: 'Bench depth efficiency in the second quarter.'
  }
];

export const MOCK_INVENTORY_SUMMARY = PREPOPULATED_SUMMARY;

export const MOCK_INVENTORY_ITEMS = PREPOPULATED_CARDS.slice(0, 5).map(card => ({
  id: card.id,
  image: card.image,
  cardName: `${card.year} ${card.manufacturer} ${card.player}`,
  status: card.isGraded ? 'Graded' : 'Raw',
  quantity: 1,
  marketValue: card.currentValue,
  purchasePrice: card.purchasePrice
}));

export const MOCK_ACQUISITION_TARGETS = [
  {
    id: '1',
    name: 'Jackson Holliday',
    team: 'BAL',
    league: 'MiLB',
    focus: 'Prospect',
    marketTrend: 'rising',
    confidence: 92,
    reason: 'Underlying contact metrics suggest elite MLB transition floor.',
    targetPrice: 250,
    image: 'https://img.mlbstatic.com/mlb-photos/person/702616.jpg'
  }
];

