import { SubscriptionTier } from "../components/TierGate";

export type RouteTierEntry = { tier: SubscriptionTier; featureName: string };

export const ROUTE_TIER_MAP: Record<string, RouteTierEntry> = {
  // ─── basic tier ($9.90/mo) ───────────────────────────────────────────
  "/price-prediction": { tier: "basic", featureName: "Price Prediction" },
  "/smart-notifications": { tier: "basic", featureName: "Smart Notifications" },
  "/market-replay": { tier: "basic", featureName: "Market Replay" },
  "/social-feed": { tier: "basic", featureName: "Social Feed" },
  "/social-trading": { tier: "basic", featureName: "Social Trading" },
  "/community-trading": { tier: "basic", featureName: "Community Trading" },
  "/achievement-system": { tier: "basic", featureName: "Achievement System" },
  "/card-show-planner": { tier: "basic", featureName: "Card Show Planner" },
  "/rip-flip-sim": { tier: "basic", featureName: "Rip & Flip Simulator" },
  "/nfl-hub": { tier: "basic", featureName: "NFL Hub" },
  "/nba-hub": { tier: "basic", featureName: "NBA Hub" },
  "/nhl-hub": { tier: "basic", featureName: "NHL Hub" },
  "/soccer-hub": { tier: "basic", featureName: "Soccer Hub" },
  "/notification-center": { tier: "basic", featureName: "Notification Center" },
  "/grading-prep": { tier: "basic", featureName: "Grading Prep" },
  "/hobby-income": { tier: "basic", featureName: "Hobby Income Tracker" },
  "/scan-to-value": { tier: "basic", featureName: "Scan to Value" },
  "/pop-forecaster": { tier: "basic", featureName: "Pop Forecaster" },
  "/draft-night-tracker": { tier: "basic", featureName: "Draft Night Tracker" },

  // ─── pro tier ($29/mo) ───────────────────────────────────────────────
  "/tax-calculator": { tier: "pro", featureName: "Tax Calculator" },
  "/tax-report": { tier: "pro", featureName: "Tax Report" },
  "/portfolio-stress-test": { tier: "pro", featureName: "Portfolio Stress Test" },
  "/portfolio-benchmark": { tier: "pro", featureName: "Portfolio Benchmark" },
  "/portfolio-attribution": { tier: "pro", featureName: "Portfolio Attribution" },
  "/portfolio-narrator": { tier: "pro", featureName: "Portfolio Narrator" },
  "/collection-appraiser": { tier: "pro", featureName: "Collection Appraiser" },
  "/collection-genome": { tier: "pro", featureName: "Collection Genome" },
  "/cross-asset-correlation": { tier: "pro", featureName: "Cross-Asset Correlation" },
  "/real-time-price-engine": { tier: "pro", featureName: "Real-Time Price Engine" },
  "/predictive-price-engine": { tier: "pro", featureName: "Predictive Price Engine" },
  "/ai-card-scanner": { tier: "pro", featureName: "AI Card Scanner" },
  "/cross-platform-arbitrage": { tier: "pro", featureName: "Cross-Platform Arbitrage" },
  "/international-arbitrage": { tier: "pro", featureName: "International Arbitrage" },
  "/consensus-pricing": { tier: "pro", featureName: "Consensus Pricing" },
  "/live-break-roi": { tier: "pro", featureName: "Live Break ROI" },
  "/auction-sniper": { tier: "pro", featureName: "Auction Sniper" },
  "/listing-optimizer": { tier: "pro", featureName: "Listing Optimizer" },
  "/grading-auditor": { tier: "pro", featureName: "Grading Auditor" },
  "/vintage-market": { tier: "pro", featureName: "Vintage Market" },
  "/vintage-allocation": { tier: "pro", featureName: "Vintage Allocation" },
  "/sealed-product": { tier: "pro", featureName: "Sealed Product Analytics" },
  "/blockchain-provenance": { tier: "pro", featureName: "Blockchain Provenance" },
  "/insurance-vault": { tier: "pro", featureName: "Insurance Vault" },
  "/slab-verification": { tier: "pro", featureName: "Slab Verification" },
  "/grade-prediction": { tier: "pro", featureName: "Grade Prediction" },
  "/grading-turnaround": { tier: "pro", featureName: "Grading Turnaround" },
  "/error-card": { tier: "pro", featureName: "Error Card Analytics" },
  "/consignment-market": { tier: "pro", featureName: "Consignment Market" },
  "/dashboard-builder": { tier: "pro", featureName: "Dashboard Builder" },
  "/research-reports": { tier: "pro", featureName: "Research Reports" },
  "/quant-workbench": { tier: "pro", featureName: "Quant Workbench" },
  "/market-indices": { tier: "pro", featureName: "Market Indices" },
  "/weather-impact": { tier: "pro", featureName: "Weather Impact" },
  "/wax-intelligence": { tier: "pro", featureName: "Wax Intelligence" },
  "/print-run-intelligence": { tier: "pro", featureName: "Print Run Intelligence" },
  "/hof-tracker": { tier: "pro", featureName: "HOF Tracker" },
  "/parallel-universe": { tier: "pro", featureName: "Parallel Universe" },
  "/sentiment-radar": { tier: "pro", featureName: "Sentiment Radar" },
  "/estate-planning": { tier: "pro", featureName: "Estate Planning" },
  "/rebalancer": { tier: "pro", featureName: "Portfolio Rebalancer" },
  "/trade-deadline": { tier: "pro", featureName: "Trade Deadline" },
  "/deal-room": { tier: "pro", featureName: "Deal Room" },
  "/live-breaks": { tier: "pro", featureName: "Live Breaks" },
  "/p2p-marketplace": { tier: "pro", featureName: "P2P Marketplace" },
  "/consignment-router": { tier: "pro", featureName: "Consignment Router" },
  "/transaction-wire": { tier: "pro", featureName: "Transaction Wire" },
  "/live-break-hub": { tier: "pro", featureName: "Live Break Hub" },
  "/compliance-center": { tier: "pro", featureName: "Compliance Center" },
  "/data-consolidation": { tier: "pro", featureName: "Data Consolidation" },
  "/vault-security": { tier: "pro", featureName: "Vault Security" },

  // v5.0 batch 1 & 2 (card-genome-sequencer through chaos-theory-simulator)
  "/card-genome-sequencer": { tier: "pro", featureName: "Card Genome Sequencer" },
  "/micro-market-scanner": { tier: "pro", featureName: "Micro Market Scanner" },
  "/momentum-tracker": { tier: "pro", featureName: "Momentum Tracker" },
  "/supply-shock-detector": { tier: "pro", featureName: "Supply Shock Detector" },
  "/price-memory-mapper": { tier: "pro", featureName: "Price Memory Mapper" },
  "/liquidity-heatmap": { tier: "pro", featureName: "Liquidity Heatmap" },
  "/collector-behavior-engine": { tier: "pro", featureName: "Collector Behavior Engine" },
  "/market-maker-simulator": { tier: "pro", featureName: "Market Maker Simulator" },
  "/fatigue-index": { tier: "pro", featureName: "Fatigue Index" },
  "/chaos-theory-simulator": { tier: "pro", featureName: "Chaos Theory Simulator" },

  // v5.1 batch 3 (sentiment-volatility-index through market-regime-detector)
  "/sentiment-volatility-index": { tier: "pro", featureName: "Sentiment Volatility Index" },
  "/whale-shadow-tracker": { tier: "pro", featureName: "Whale Shadow Tracker" },
  "/grading-arbitrage-engine": { tier: "pro", featureName: "Grading Arbitrage Engine" },
  "/temporal-price-warp": { tier: "pro", featureName: "Temporal Price Warp" },
  "/collection-decay-monitor": { tier: "pro", featureName: "Collection Decay Monitor" },
  "/market-regime-detector": { tier: "pro", featureName: "Market Regime Detector" },

  // v5.0 round 3 (options-desk through portfolio-dna-rebalancer)
  "/options-desk": { tier: "pro", featureName: "Options Desk" },
  "/card-futures": { tier: "pro", featureName: "Card Futures" },
  "/synthetic-index-creator": { tier: "pro", featureName: "Synthetic Index Creator" },
  "/risk-parity-optimizer": { tier: "pro", featureName: "Risk Parity Optimizer" },
  "/volatility-surface": { tier: "pro", featureName: "Volatility Surface" },
  "/multi-factor-model": { tier: "pro", featureName: "Multi-Factor Model" },
  "/portfolio-dna-rebalancer": { tier: "pro", featureName: "Portfolio DNA Rebalancer" },

  // v6.0 (injury-shockwave through biometric-trading-guard)
  "/injury-shockwave": { tier: "pro", featureName: "Injury Shockwave" },
  "/rookie-trajectory": { tier: "pro", featureName: "Rookie Trajectory" },
  "/career-arc-modeler": { tier: "pro", featureName: "Career Arc Modeler" },
  "/championship-odds-valuator": { tier: "pro", featureName: "Championship Odds Valuator" },
  "/media-sentiment-tracker": { tier: "pro", featureName: "Media Sentiment Tracker" },
  "/social-momentum-indicator": { tier: "pro", featureName: "Social Momentum Indicator" },
  "/viral-spike-detector": { tier: "pro", featureName: "Viral Spike Detector" },
  "/influencer-impact-scorer": { tier: "pro", featureName: "Influencer Impact Scorer" },
  "/narrative-price-engine": { tier: "pro", featureName: "Narrative Price Engine" },
  "/hype-cycle-tracker": { tier: "pro", featureName: "Hype Cycle Tracker" },
  "/fomo-index": { tier: "pro", featureName: "FOMO Index" },
  "/contrarian-signal-finder": { tier: "pro", featureName: "Contrarian Signal Finder" },
  "/biometric-trading-guard": { tier: "pro", featureName: "Biometric Trading Guard" },

  // Advanced trading (live-game-impact-engine through draft-war-room)
  "/live-game-impact-engine": { tier: "pro", featureName: "Live Game Impact Engine" },
  "/play-by-play-valuation": { tier: "pro", featureName: "Play-by-Play Valuation" },
  "/stat-milestone-tracker": { tier: "pro", featureName: "Stat Milestone Tracker" },
  "/injury-report-parser": { tier: "pro", featureName: "Injury Report Parser" },
  "/trade-rumor-analyzer": { tier: "pro", featureName: "Trade Rumor Analyzer" },
  "/draft-war-room": { tier: "pro", featureName: "Draft War Room" },

  // v6.1 (dopamine-cycle-tracker through centering-analyzer)
  "/dopamine-cycle-tracker": { tier: "pro", featureName: "Dopamine Cycle Tracker" },
  "/fomo-guard": { tier: "pro", featureName: "FOMO Guard" },
  "/loss-aversion-coach": { tier: "pro", featureName: "Loss Aversion Coach" },
  "/sunk-cost-analyzer": { tier: "pro", featureName: "Sunk Cost Analyzer" },
  "/confirmation-bias-checker": { tier: "pro", featureName: "Confirmation Bias Checker" },
  "/endowment-effect-calculator": { tier: "pro", featureName: "Endowment Effect Calculator" },
  "/anchoring-detector": { tier: "pro", featureName: "Anchoring Detector" },
  "/herd-mentality-index": { tier: "pro", featureName: "Herd Mentality Index" },
  "/patience-profit-tracker": { tier: "pro", featureName: "Patience Profit Tracker" },
  "/centering-analyzer": { tier: "pro", featureName: "Centering Analyzer" },

  // v7.0 (regulatory-compliance-radar through generational-demand-forecaster)
  "/regulatory-compliance-radar": { tier: "pro", featureName: "Regulatory Compliance Radar" },
  "/tax-loss-harvesting": { tier: "pro", featureName: "Tax Loss Harvesting" },
  "/customs-duty-calculator": { tier: "pro", featureName: "Customs Duty Calculator" },
  "/anti-fraud-sentinel": { tier: "pro", featureName: "Anti-Fraud Sentinel" },
  "/counterfeit-detector": { tier: "pro", featureName: "Counterfeit Detector" },
  "/market-manipulation-scanner": { tier: "pro", featureName: "Market Manipulation Scanner" },
  "/wash-sale-tracker": { tier: "pro", featureName: "Wash Sale Tracker" },
  "/generational-demand-forecaster": { tier: "pro", featureName: "Generational Demand Forecaster" },

  // v7.1 (slab-case-forensics through vintage-provenance)
  "/slab-case-forensics": { tier: "pro", featureName: "Slab Case Forensics" },
  "/population-report-analyzer": { tier: "pro", featureName: "Population Report Analyzer" },
  "/grade-inflation-tracker": { tier: "pro", featureName: "Grade Inflation Tracker" },
  "/crossover-candidate-finder": { tier: "pro", featureName: "Crossover Candidate Finder" },
  "/mechanical-grade-predictor": { tier: "pro", featureName: "Mechanical Grade Predictor" },
  "/vintage-provenance": { tier: "pro", featureName: "Vintage Provenance" },

  // v8.0 frontier (auction-equilibrium through opportunity-cost-phantom)
  "/auction-equilibrium": { tier: "pro", featureName: "Auction Equilibrium" },
  "/price-elasticity-modeler": { tier: "pro", featureName: "Price Elasticity Modeler" },
  "/scarcity-premium-calculator": { tier: "pro", featureName: "Scarcity Premium Calculator" },
  "/network-effect-valuator": { tier: "pro", featureName: "Network Effect Valuator" },
  "/information-asymmetry-detector": { tier: "pro", featureName: "Information Asymmetry Detector" },
  "/opportunity-cost-phantom": { tier: "pro", featureName: "Opportunity Cost Phantom" },

  // v5.1+ frontier (agent-outcome-memory through agent-personality)
  "/agent-outcome-memory": { tier: "pro", featureName: "Agent Outcome Memory" },
  "/agent-strategy-evolution": { tier: "pro", featureName: "Agent Strategy Evolution" },
  "/agent-confidence-calibrator": { tier: "pro", featureName: "Agent Confidence Calibrator" },
  "/agent-personality": { tier: "pro", featureName: "Agent Personality" },

  // v5.2 (bid-ask-spread-predictor through agent-confidence-history)
  "/bid-ask-spread-predictor": { tier: "pro", featureName: "Bid-Ask Spread Predictor" },
  "/market-depth-visualizer": { tier: "pro", featureName: "Market Depth Visualizer" },
  "/order-flow-analyzer": { tier: "pro", featureName: "Order Flow Analyzer" },
  "/smart-money-tracker": { tier: "pro", featureName: "Smart Money Tracker" },
  "/agent-confidence-history": { tier: "pro", featureName: "Agent Confidence History" },

  // Formerly coming-soon (what-if-simulator through wax-break-roi-tracker)
  "/what-if-simulator": { tier: "pro", featureName: "What-If Simulator" },
  "/set-registry": { tier: "pro", featureName: "Set Registry" },
  "/prospect-tracker": { tier: "pro", featureName: "Prospect Tracker" },
  "/multi-sport-arbitrage": { tier: "pro", featureName: "Multi-Sport Arbitrage" },
  "/wax-break-roi-tracker": { tier: "pro", featureName: "Wax Break ROI Tracker" },

  // Industry-first v11 (regret-minimization-engine through cross-hobby-arbitrage-bridge)
  "/regret-minimization-engine": { tier: "pro", featureName: "Regret Minimization Engine" },
  "/nostalgia-premium-calculator": { tier: "pro", featureName: "Nostalgia Premium Calculator" },
  "/completion-obsession-optimizer": { tier: "pro", featureName: "Completion Obsession Optimizer" },
  "/tribal-affiliation-valuator": { tier: "pro", featureName: "Tribal Affiliation Valuator" },
  "/delayed-gratification-modeler": { tier: "pro", featureName: "Delayed Gratification Modeler" },
  "/cross-hobby-arbitrage-bridge": { tier: "pro", featureName: "Cross-Hobby Arbitrage Bridge" },

  // ─── alpha tier ($99/mo) ─────────────────────────────────────────────
  "/api-platform": { tier: "alpha", featureName: "API Platform" },
  "/msi-terminal": { tier: "alpha", featureName: "MSI Terminal" },
  "/derivatives-desk": { tier: "alpha", featureName: "Derivatives Desk" },
  "/predictive-market-maker": { tier: "alpha", featureName: "Predictive Market Maker" },
  "/autonomous-acquisition": { tier: "alpha", featureName: "Autonomous Acquisition" },
  "/copy-trading": { tier: "alpha", featureName: "Copy Trading" },
  "/influence-graph": { tier: "alpha", featureName: "Influence Graph" },
  "/cross-hobby-portfolio": { tier: "alpha", featureName: "Cross-Hobby Portfolio" },
  "/white-label-api": { tier: "alpha", featureName: "White Label API" },
  "/dealer-inventory": { tier: "alpha", featureName: "Dealer Inventory" },
  "/fund-reporting": { tier: "alpha", featureName: "Fund Reporting" },
  "/audit-trail": { tier: "alpha", featureName: "Audit Trail" },
  "/ar-showcase": { tier: "alpha", featureName: "AR Showcase" },
  "/frontier-lab": { tier: "alpha", featureName: "Frontier Lab" },
  "/phase-ops": { tier: "alpha", featureName: "Phase Operations" },

  // Group/community features
  "/shared-watchlists": { tier: "alpha", featureName: "Shared Watchlists" },
  "/group-breaks": { tier: "alpha", featureName: "Group Breaks" },
  "/club-management": { tier: "alpha", featureName: "Club Management" },
  "/collective-grading": { tier: "alpha", featureName: "Collective Grading" },
  "/shared-dashboards": { tier: "alpha", featureName: "Shared Dashboards" },
  "/rbac-teams": { tier: "alpha", featureName: "RBAC Teams" },
  "/collaborative-set-registry": { tier: "alpha", featureName: "Collaborative Set Registry" },
  "/card-show-squad": { tier: "alpha", featureName: "Card Show Squad" },
  "/group-buy-coop": { tier: "alpha", featureName: "Group Buy Co-op" },
  "/draft-night-war-room": { tier: "alpha", featureName: "Draft Night War Room" },
  "/mentorship-exchange": { tier: "alpha", featureName: "Mentorship Exchange" },
  "/dispute-arbitration": { tier: "alpha", featureName: "Dispute Arbitration" },
  "/group-insurance": { tier: "alpha", featureName: "Group Insurance" },
  "/crowd-pricing": { tier: "alpha", featureName: "Crowd Pricing" },
  "/group-vault": { tier: "alpha", featureName: "Group Vault" },
  "/swap-meet": { tier: "alpha", featureName: "Swap Meet" },
};

export function getRouteTier(path: string): RouteTierEntry | null {
  return ROUTE_TIER_MAP[path] ?? null;
}
