import { FEATURED_FEATURE_IDS, SEARCHABLE_FEATURE_IDS } from './productSurface';
import type { Feature, FeatureStatus, FeatureTier } from './featureTypes';
import { FEATURE_CATALOG_ROUTE_SUPPLEMENT } from './featureCatalogRouteSupplement';

export type { Feature, FeatureStatus, FeatureTier } from './featureTypes';

/**
 * Feature Catalog — master registry of platform features
 * organized by tier and category. Used by FeatureSearch, FeatureDirectory,
 * and GuidedTour components.
 */

const FEATURE_CATALOG_CORE: Feature[] = [
  // ─── Core (Phases 1-14) ─────────────────────────────────
  { id: 'dashboard', name: 'League Intelligence Dashboard', description: 'Dynamic NAV calculation, financial intelligence, and league HUD with P/L tracking.', tier: 'Core', category: 'Portfolio', status: 'live', path: '/', icon: 'LayoutDashboard', phase: 1, keywords: ['nav', 'portfolio', 'home', 'overview'] },
  { id: 'collection', name: 'Collection & Inventory', description: 'Automated ingestion, inventory management, sold vault, and grading support.', tier: 'Core', category: 'Portfolio', status: 'live', path: '/collection', icon: 'Layers', phase: 2, keywords: ['cards', 'inventory', 'vault'] },
  { id: 'market-pulse', name: 'Market Pulse Intelligence', description: 'Sentiment analysis, alpha correlation, and lagging alpha alerts.', tier: 'Core', category: 'Analytics', status: 'live', path: '/', icon: 'Activity', phase: 3, keywords: ['sentiment', 'alpha', 'market'] },
  { id: 'ai-discovery', name: 'AI Discovery Engine', description: 'Automated valuation, live market sync, and prospect discovery via Gemini.', tier: 'Core', category: 'AI', status: 'live', path: '/', icon: 'Sparkles', phase: 4, keywords: ['gemini', 'ai', 'valuation', 'sync'] },
  { id: 'watchlist', name: 'Watchlist & Comparison', description: 'Target price alerts and side-by-side comparative analysis.', tier: 'Core', category: 'Trading', status: 'live', path: '/favorites', icon: 'Star', phase: 5, keywords: ['targets', 'watch', 'compare'] },
  { id: 'negotiation-arena', name: 'AI Negotiation Arena', description: 'Real-time chat negotiation with AI sellers using Gemini, with sentiment tracking.', tier: 'Core', category: 'Trading', status: 'live', path: '/', icon: 'Gavel', phase: 6, keywords: ['negotiate', 'buy', 'deal', 'chat'] },
  { id: 'deep-search', name: 'Deep Search Intelligence', description: 'Semantic AI search by vibe, era, trajectory, or card similarity.', tier: 'Core', category: 'AI', status: 'live', path: '/deep-search', icon: 'Search', phase: 7, keywords: ['search', 'semantic', 'find', 'similar'] },
  { id: 'image-lightbox', name: 'Image Lightbox', description: 'Full-screen professional image viewing with keyboard navigation.', tier: 'Core', category: 'UX', status: 'live', path: null, icon: 'Image', phase: 8, keywords: ['image', 'zoom', 'lightbox', 'photo'] },
  { id: 'auth-system', name: 'Authentication System', description: 'Supabase auth with login, signup, password reset, and demo mode.', tier: 'Core', category: 'System', status: 'live', path: '/login', icon: 'Shield', phase: 9, keywords: ['login', 'auth', 'account'] },
  { id: 'billing', name: 'Stripe Billing', description: 'Multi-tier subscription system with usage-based pricing.', tier: 'Core', category: 'System', status: 'live', path: '/billing', icon: 'CreditCard', phase: 10, keywords: ['billing', 'subscription', 'stripe', 'payment'] },
  { id: 'mlb-stats', name: 'PressBox Hub', description: 'MLB API integration for live stats, player lookup, and performance data.', tier: 'Core', category: 'Data', status: 'live', path: '/mlb-stats', icon: 'Trophy', phase: 11, keywords: ['mlb', 'stats', 'baseball', 'pressbox'] },
  { id: 'players', name: 'Player Directory', description: 'Browse and search players across leagues with breakout scores.', tier: 'Core', category: 'Data', status: 'live', path: '/players', icon: 'Users', phase: 12, keywords: ['players', 'athletes', 'roster'] },
  { id: 'scarcity-intel', name: 'Scarcity Intelligence', description: 'Population reporting, pop badges, and Pop 1 alerts.', tier: 'Core', category: 'Analytics', status: 'live', path: null, icon: 'Gem', phase: 13, keywords: ['scarcity', 'pop', 'population', 'rare'] },
  { id: 'social-alpha', name: 'Social Alpha Elite', description: 'Live hype feed and institutional collector tiers.', tier: 'Core', category: 'Social', status: 'live', path: '/', icon: 'Flame', phase: 14, keywords: ['social', 'hype', 'feed', 'tiers'] },

  // ─── Competitive Moat (Phases 15-38) ────────────────────
  { id: 'mobile-native', name: 'Mobile Native PWA', description: 'Service worker caching, background sync, haptic feedback, and swipeable cards.', tier: 'Competitive Moat', category: 'UX', status: 'live', path: null, icon: 'Smartphone', phase: 15, keywords: ['mobile', 'pwa', 'offline', 'swipe'] },
  { id: 'agentic-negotiation', name: 'Agentic Negotiation', description: 'Campaigns, playbooks, negotiations, escrow timelines, activity feed, and acquisition results persist in MSI store; analytics KPIs and monthly charts derive from stored acquisition rows. All execution remains simulated demo data with in-modal disclosure — not live marketplace trading.', tier: 'Competitive Moat', category: 'Trading', status: 'live', path: '/autonomous-acquisition', icon: 'Bot', phase: 16, keywords: ['agent', 'playbook', 'auto-negotiate'] },
  { id: 'liquidity-pool', name: 'Institutional Liquidity Pool', description: 'MSI House instant-liquidity concept and payout logic, currently staged as a beta workflow.', tier: 'Competitive Moat', category: 'Trading', status: 'beta', path: null, icon: 'Droplets', phase: 17, keywords: ['instant', 'sell', 'liquidity', 'house'] },
  { id: 'predictive-alpha', name: 'Predictive Alpha Engine', description: 'Trajectory and breakout scoring from inventory, MSI price snapshots, liquidity, and scarcity; signal modes (historical_only / hybrid / imported_comps) and confidence breakdown in the modal; optional imported comp anchors via price history — not third-party market execution.', tier: 'Competitive Moat', category: 'Analytics', status: 'live', path: '/', icon: 'TrendingUp', phase: 18, keywords: ['predict', 'forecast', 'breakout', 'alpha'] },
  { id: 'multi-agent', name: 'Multi-Agent Intelligence', description: 'War Room Gemini committee on /war-room with last thesis cached in MSI store, deterministic input fingerprint + prompt version + model id on each run, JSON export for support/audit, and agent recommendations in local agent data (cloud upsert when Supabase is configured and not in demo isolation). LLM wording is not reproducible; inputs and trace metadata are.', tier: 'Competitive Moat', category: 'AI', status: 'live', path: '/war-room', icon: 'Brain', phase: 19, keywords: ['agent', 'atlas', 'apex', 'sentinel', 'viper'] },
  { id: 'liquidity-intel', name: 'Liquidity Intelligence', description: 'Order book simulation, market impact, volume velocity, and liquidity heatmap.', tier: 'Competitive Moat', category: 'Analytics', status: 'live', path: null, icon: 'BarChart3', phase: 20, keywords: ['liquidity', 'order book', 'depth', 'velocity'] },
  { id: 'cross-correlation', name: 'Cross-Asset Correlation', description: 'Cross-asset correlation, diversification, and drawdown views on synthetic seeded series; full-page experience at /cross-asset-correlation with on-screen data-source disclosure.', tier: 'Competitive Moat', category: 'Analytics', status: 'live', path: '/cross-asset-correlation', icon: 'GitBranch', phase: 21, keywords: ['correlation', 'hedge', 'diversification'] },
  { id: 'fiscal-intel', name: 'Fiscal Intelligence', description: 'Tax-lot analysis, Schedule D-style exports, and holding-period tracking from recorded transactions.', tier: 'Competitive Moat', category: 'Finance', status: 'live', path: null, icon: 'Calculator', phase: 22, keywords: ['tax', 'cost basis', 'schedule d', 'fiscal'] },
  { id: 'visual-audit', name: 'Visual Audit Simulation', description: 'Pre-grade intelligence with ROI overlays and simulated scoring; grade probabilities are estimates only.', tier: 'Competitive Moat', category: 'AI', status: 'live', path: '/pre-grade-intelligence', icon: 'ScanEye', phase: 23, keywords: ['grade', 'predict', 'audit', 'sub-grade'] },
  { id: 'macro-sentinel', name: 'Macro-Sentinel Monitoring', description: 'Early warning system for global market shifts affecting luxury assets.', tier: 'Competitive Moat', category: 'Analytics', status: 'live', path: null, icon: 'Radar', phase: 24, keywords: ['macro', 'sentinel', 'economy', 'warning'] },
  { id: 'break-even', name: 'Break-Even Calculator', description: 'Minimum sale price needed after all marketplace fees.', tier: 'Competitive Moat', category: 'Finance', status: 'live', path: null, icon: 'Scale', phase: 25, keywords: ['break even', 'fees', 'profit', 'calculator'] },
  { id: 'insurance-report', name: 'Insurance Valuation Report', description: 'Insurance-ready valuation exports with itemized inventory and heuristic replacement-cost estimates.', tier: 'Competitive Moat', category: 'Finance', status: 'live', path: null, icon: 'FileCheck', phase: 26, keywords: ['insurance', 'valuation', 'report'] },
  { id: 'collector-audit-dossier', name: 'Collector Audit Dossier', description: 'Unified collector operating record combining tax posture, insurance readiness, and exit routing in one exportable workflow.', tier: 'Competitive Moat', category: 'Finance', status: 'live', path: '/audit-dossier', icon: 'BriefcaseBusiness', phase: 27, keywords: ['audit', 'dossier', 'tax', 'insurance', 'exit'] },
  { id: 'what-if', name: 'What-If Simulator', description: 'Trade-scenario planning workspace for NAV and diversification changes.', tier: 'Competitive Moat', category: 'Analytics', status: 'live', path: '/what-if-simulator', icon: 'FlaskConical', phase: 27, keywords: ['simulate', 'what if', 'trade', 'test'] },
  { id: 'grading-planner', name: 'Grading Batch Planner', description: 'Batch grading planner for expected ROI and submission tiers.', tier: 'Competitive Moat', category: 'Tools', status: 'live', path: '/grading-batch-planner', icon: 'ClipboardList', phase: 28, keywords: ['grading', 'batch', 'submission', 'roi'] },
  { id: 'ebay-listing', name: 'eBay Listing Generator', description: 'SEO-oriented listing draft generation for sale preparation workflows.', tier: 'Competitive Moat', category: 'Trading', status: 'live', path: '/ebay-listing-generator', icon: 'ShoppingBag', phase: 29, keywords: ['ebay', 'listing', 'sell', 'seo'] },
  { id: 'collection-share', name: 'Collection Sharing', description: 'Shareable collection snapshots with embeddable HTML widgets.', tier: 'Competitive Moat', category: 'Social', status: 'live', path: null, icon: 'Share2', phase: 30, keywords: ['share', 'embed', 'widget', 'public'] },
  { id: 'wax-break-roi', name: 'Wax Break ROI Tracker', description: 'Break ROI logging workflow for sealed wax participants.', tier: 'Competitive Moat', category: 'Tools', status: 'live', path: '/wax-break-roi-tracker', icon: 'Package', phase: 31, keywords: ['wax', 'break', 'box', 'roi'] },
  { id: 'usability', name: 'Usability & Accessibility', description: 'Keyboard shortcuts, command palette, undo toasts, skeleton loaders, and ARIA.', tier: 'Competitive Moat', category: 'UX', status: 'live', path: null, icon: 'Accessibility', phase: 32, keywords: ['keyboard', 'accessibility', 'ux', 'shortcuts'] },
  { id: 'rebalance-alerts', name: 'Rebalancing Alerts', description: 'Automated alerts when portfolio drift exceeds configurable thresholds.', tier: 'Competitive Moat', category: 'Analytics', status: 'live', path: null, icon: 'RefreshCw', phase: 33, keywords: ['rebalance', 'drift', 'allocation'] },
  { id: 'auction-sniper', name: 'Auction Sniper', description: 'Auction monitoring and bid-timing concept pending marketplace integration.', tier: 'Competitive Moat', category: 'Trading', status: 'live', path: '/auction-sniper', icon: 'Crosshair', phase: 34, keywords: ['auction', 'snipe', 'bid', 'timer'] },
  { id: 'consignment', name: 'Consignment Tracker', description: 'Mark cards on consignment with a partner snapshot embedded in inventory (syncs with Supabase when signed in). Fee and house comparison UIs use illustrative models only—verify real terms with each venue.', tier: 'Competitive Moat', category: 'Trading', status: 'live', path: '/collection', icon: 'Truck', phase: 35, keywords: ['consignment', 'pwcc', 'goldin', 'heritage'] },
  { id: 'price-history', name: 'Price History Charts', description: 'Interactive time-series charts with SMA, Bollinger Bands, and statistics.', tier: 'Competitive Moat', category: 'Analytics', status: 'live', path: null, icon: 'LineChart', phase: 36, keywords: ['price', 'chart', 'history', 'technical'] },
  { id: 'achievements', name: 'Collection Achievements', description: 'Gamification with 30+ badges across 5 tiers and level progression.', tier: 'Competitive Moat', category: 'Social', status: 'live', path: null, icon: 'Award', phase: 37, keywords: ['achievement', 'badge', 'level', 'gamification'] },
  { id: 'anomaly-detection', name: 'Market Anomaly Detection', description: 'Heuristic anomaly detection on your MSI inventory (purchase vs value, sport averages, stale valuations, simulated volume signal); arbitrage rows are modeled venues; max 2 alerts per card; dashboard widget on /.', tier: 'Competitive Moat', category: 'Analytics', status: 'live', path: '/', icon: 'AlertTriangle', phase: 38, keywords: ['anomaly', 'spike', 'crash', 'arbitrage'] },

  // ─── Advanced Intelligence (Phases 39-63) ───────────────
  { id: 'trade-block', name: 'Trade Block & Offers', description: 'Organize cards for trade, evaluate offers, and manage multi-card package deals.', tier: 'Advanced Intelligence', category: 'Trading', status: 'live', path: null, icon: 'ArrowLeftRight', phase: 39, keywords: ['trade', 'offer', 'block', 'swap'] },
  { id: 'market-watchlist', name: 'Market Watchlists & Alerts', description: 'Track unowned cards with configurable price alert rules.', tier: 'Advanced Intelligence', category: 'Trading', status: 'live', path: null, icon: 'Eye', phase: 40, keywords: ['watchlist', 'alert', 'price target'] },
  { id: 'analytics-reports', name: 'Analytics Reports & Export', description: 'Generate PDF-style portfolio, tax, insurance, and performance reports.', tier: 'Advanced Intelligence', category: 'Finance', status: 'live', path: null, icon: 'FileSpreadsheet', phase: 41, keywords: ['report', 'export', 'pdf', 'csv'] },
  { id: 'benchmarking', name: 'Community Benchmarking', description: 'Compare performance against community and compete on leaderboards.', tier: 'Advanced Intelligence', category: 'Social', status: 'live', path: '/leaderboard', icon: 'Trophy', phase: 42, keywords: ['benchmark', 'leaderboard', 'rank', 'community'] },
  { id: 'smart-advisor', name: 'Smart Collection Advisor', description: 'AI-driven buy/sell recommendations with gap analysis and strategy profiles.', tier: 'Advanced Intelligence', category: 'AI', status: 'live', path: null, icon: 'Lightbulb', phase: 43, keywords: ['advisor', 'recommend', 'strategy', 'gap'] },
  { id: 'set-registry', name: 'Set Completion Registry', description: 'Track progress toward completing card sets with missing card finder.', tier: 'Advanced Intelligence', category: 'Tools', status: 'live', path: null, icon: 'CheckSquare', phase: 44, keywords: ['set', 'complete', 'checklist', 'registry'] },
  { id: 'time-machine', name: 'Portfolio Time Machine', description: 'View portfolio at any historical date with period comparison and decision journal.', tier: 'Advanced Intelligence', category: 'Analytics', status: 'live', path: null, icon: 'Clock', phase: 45, keywords: ['time machine', 'history', 'snapshot', 'compare'] },
  { id: 'rules-engine', name: 'Automated Trading Rules', description: 'Conditional rules with backtesting that auto-trigger portfolio actions.', tier: 'Advanced Intelligence', category: 'Trading', status: 'live', path: null, icon: 'Workflow', phase: 46, keywords: ['rules', 'automate', 'backtest', 'trigger'] },
  { id: 'technical-analysis', name: 'Technical Analysis Suite', description: 'RSI, MACD, Fibonacci, volume profile, and candlestick pattern detection.', tier: 'Advanced Intelligence', category: 'Analytics', status: 'live', path: null, icon: 'CandlestickChart', phase: 47, keywords: ['rsi', 'macd', 'fibonacci', 'technical'] },
  { id: 'data-import', name: 'Data Import Hub', description: 'Bulk import from CSV, eBay, PSA/BGS cert lookup, and external sync.', tier: 'Advanced Intelligence', category: 'Tools', status: 'live', path: null, icon: 'Upload', phase: 48, keywords: ['import', 'csv', 'ebay', 'sync', 'bulk'] },
  { id: 'social-network', name: 'Social Network & Messaging', description: 'Follow collectors, direct messages, trade matching, and activity feeds.', tier: 'Advanced Intelligence', category: 'Social', status: 'live', path: null, icon: 'MessageSquare', phase: 49, keywords: ['social', 'message', 'follow', 'chat'] },
  { id: 'wax-invest', name: 'Sealed Wax Tracker', description: 'Track sealed box investments with hold-vs-rip analysis.', tier: 'Advanced Intelligence', category: 'Tools', status: 'live', path: null, icon: 'Box', phase: 50, keywords: ['sealed', 'wax', 'box', 'hold', 'rip'] },
  { id: 'counterfeit-intel', name: 'Counterfeit Detection', description: 'AI authentication scoring, cert verification, and seller risk analysis.', tier: 'Advanced Intelligence', category: 'AI', status: 'live', path: null, icon: 'ShieldAlert', phase: 51, keywords: ['counterfeit', 'auth', 'fake', 'verify'] },
  { id: 'player-index', name: 'Player Market Index', description: 'Player-level market indexes, career arc modeling, and hot/cold lists.', tier: 'Advanced Intelligence', category: 'Analytics', status: 'live', path: null, icon: 'BarChart', phase: 52, keywords: ['player index', 'career', 'hot', 'cold'] },
  { id: 'showcase', name: 'Digital Display Case', description: 'Build visual showcases with themed backgrounds and shareable URLs.', tier: 'Advanced Intelligence', category: 'Social', status: 'live', path: null, icon: 'Monitor', phase: 53, keywords: ['showcase', 'display', 'gallery', 'share'] },
  { id: 'grade-premium', name: 'Grade Premium Analytics', description: 'Grade-over-grade price multipliers and crossover ROI calculator.', tier: 'Advanced Intelligence', category: 'Analytics', status: 'live', path: null, icon: 'Gem', phase: 54, keywords: ['grade', 'premium', 'crossover', 'psa', 'bgs'] },
  { id: 'deal-finder', name: 'Deal Finder & Arbitrage', description: 'Surface underpriced cards across platforms with deal scoring.', tier: 'Advanced Intelligence', category: 'Trading', status: 'live', path: null, icon: 'Percent', phase: 55, keywords: ['deal', 'arbitrage', 'underpriced', 'savings'] },
  { id: 'insurance-manager', name: 'Insurance Policy Manager', description: 'Track policies, premiums, coverage gaps, and renewal reminders.', tier: 'Advanced Intelligence', category: 'Finance', status: 'live', path: null, icon: 'Shield', phase: 56, keywords: ['insurance', 'policy', 'coverage', 'premium'] },
  { id: 'pop-growth', name: 'Pop Report Growth Tracker', description: 'Population report changes over time with supply/demand indicators.', tier: 'Advanced Intelligence', category: 'Analytics', status: 'live', path: null, icon: 'TrendingUp', phase: 57, keywords: ['pop', 'growth', 'supply', 'demand'] },
  { id: 'event-planner', name: 'Card Show & Event Planner', description: 'Prepare for card shows with inventory planning and deal tracking.', tier: 'Advanced Intelligence', category: 'Tools', status: 'live', path: null, icon: 'Calendar', phase: 58, keywords: ['show', 'event', 'national', 'travel'] },
  { id: 'seasonal-engine', name: 'Seasonal Strategy Engine', description: 'Buy/sell timing automation based on sport-specific seasonal patterns.', tier: 'Advanced Intelligence', category: 'Analytics', status: 'live', path: null, icon: 'Sun', phase: 59, keywords: ['seasonal', 'timing', 'buy window', 'sell window'] },
  { id: 'multi-currency', name: 'Multi-Currency & International', description: 'Currency conversion, cross-border price comparison, and duty calculator.', tier: 'Advanced Intelligence', category: 'Finance', status: 'live', path: null, icon: 'Globe', phase: 60, keywords: ['currency', 'international', 'exchange', 'duty'] },
  { id: 'prospect-pipeline', name: 'Prospect Pipeline & Draft', description: 'Deep prospect tracking from minor leagues through draft to rookie year.', tier: 'Advanced Intelligence', category: 'Data', status: 'live', path: '/prospects', icon: 'GitPullRequest', phase: 61, keywords: ['prospect', 'draft', 'pipeline', 'stash'] },
  { id: 'goal-planner', name: 'Collection Goal Planner', description: 'Financial and collection targets with progress tracking and AI planning.', tier: 'Advanced Intelligence', category: 'Tools', status: 'live', path: null, icon: 'Target', phase: 62, keywords: ['goal', 'target', 'plan', 'milestone'] },
  { id: 'alerts', name: 'Portfolio Alerts', description: 'Alert rules and portfolio-triggered notifications.', tier: 'Advanced Intelligence', category: 'System', status: 'live', path: '/alerts', icon: 'Bell', phase: 63, keywords: ['alerts', 'rules', 'portfolio'] },
  { id: 'notification-center', name: 'Notification Command Center', description: 'Unified notification hub with smart grouping, priority scoring, and digests.', tier: 'Advanced Intelligence', category: 'System', status: 'live', path: '/notification-center', icon: 'Inbox', phase: 63, keywords: ['notification', 'alert', 'inbox', 'digest', 'command center'] },

  // ─── Differentiated (Phases 64-68) ──────────────────────
  { id: 'stress-test', name: 'Monte Carlo Stress Testing', description: 'Financial-grade 1000+ simulation paths with VaR, drawdown, and scenario analysis.', tier: 'Differentiated', category: 'Analytics', status: 'live', path: null, icon: 'Activity', phase: 64, keywords: ['monte carlo', 'stress', 'var', 'risk', 'simulation'] },
  { id: 'grade-predict', name: 'AI Predictive Grading', description: 'Pre-submission grade prediction with bulk optimizer and ROI calculator.', tier: 'Differentiated', category: 'AI', status: 'live', path: null, icon: 'Cpu', phase: 65, keywords: ['predict', 'grade', 'submission', 'roi'] },
  { id: 'tax-harvest', name: 'Tax-Loss Harvesting', description: 'Strategic loss selling with wash-sale awareness and tax bracket optimization.', tier: 'Differentiated', category: 'Finance', status: 'live', path: null, icon: 'Scissors', phase: 66, keywords: ['tax', 'harvest', 'loss', 'wash sale'] },
  { id: 'cross-asset-corr', name: 'Cross-Asset Correlation', description: 'Correlate cards with S&P 500, crypto, bonds, and sports metrics.', tier: 'Differentiated', category: 'Analytics', status: 'live', path: null, icon: 'GitMerge', phase: 67, keywords: ['correlation', 'sp500', 'crypto', 'beta'] },
  { id: 'exit-velocity', name: 'Liquidity & Exit Velocity', description: 'Liquidity scoring, market depth, exit velocity, and emergency liquidation planning.', tier: 'Differentiated', category: 'Analytics', status: 'live', path: null, icon: 'Zap', phase: 68, keywords: ['liquidity', 'exit', 'velocity', 'sell speed'] },
  { id: 'liquidity-twin', name: 'Liquidity Twin', description: 'Venue-aware exit planning with synthetic spreads, time-to-exit, and order-book twins.', tier: 'Competitive Moat', category: 'Trading', status: 'live', path: '/liquidity-twin', icon: 'Zap', phase: 143, keywords: ['liquidity twin', 'exit', 'slippage', 'venue'] },
  { id: 'private-deal-room-agent', name: 'Private Deal Room Agent', description: 'Escalate sensitive listings into encrypted private negotiation rooms with agent support.', tier: 'Competitive Moat', category: 'Trading', status: 'live', path: '/private-deal-room-agent', icon: 'Lock', phase: 144, keywords: ['deal room', 'private', 'negotiation', 'agent'] },
  { id: 'counterparty-trust-graph', name: 'Counterparty Trust Graph', description: 'Persistent seller and broker trust scoring built from deals, referrals, and disputes.', tier: 'Competitive Moat', category: 'Security', status: 'live', path: '/counterparty-trust-graph', icon: 'Share2', phase: 145, keywords: ['trust graph', 'counterparty', 'reputation', 'risk'] },
  { id: 'catalyst-market', name: 'Catalyst Market', description: 'Trade and monitor event-driven opportunities tied to promotions, scarcity, and sentiment shocks.', tier: 'Competitive Moat', category: 'Analytics', status: 'live', path: '/catalyst-market', icon: 'Flame', phase: 146, keywords: ['catalyst', 'event', 'market', 'opportunity'] },
  { id: 'portfolio-scenario-theater', name: 'Portfolio Scenario Theater', description: 'Persisted Monte Carlo scenario snapshots with projected NAV and hedging guidance.', tier: 'Competitive Moat', category: 'Analytics', status: 'live', path: '/portfolio-scenario-theater', icon: 'Activity', phase: 147, keywords: ['scenario theater', 'stress test', 'simulation', 'nav'] },

  // ─── Industry-First (Phases 69-73) ──────────────────────
  { id: 'live-impact', name: 'Live Game Impact Engine', description: 'Simulated live game event feed with labeled demo/replay mode and portfolio impact estimates — not a live broadcast integration.', tier: 'Industry-First', category: 'Analytics', status: 'live', path: '/live-impact', icon: 'Radio', phase: 69, keywords: ['live', 'game', 'impact', 'real-time'] },
  { id: 'vision-grading', name: 'AI Vision Grading Lab', description: 'Computer-vision grading lab with mock defect mapping and probability outputs; estimates only — not third-party grader certification.', tier: 'Industry-First', category: 'AI', status: 'beta', path: '/grading-vision-engine', icon: 'ScanEye', phase: 70, keywords: ['vision', 'grading', 'scan', 'camera', 'defect'] },
  { id: 'fractional-vault', name: 'Fractional Vault & Copy-Trading', description: 'Fractional ownership and copy-trading showcase pending live execution rails.', tier: 'Industry-First', category: 'Trading', status: 'beta', path: '/fractional-vault', icon: 'Landmark', phase: 71, keywords: ['fractional', 'vault', 'shares', 'copy trading'] },
  { id: 'provenance-chain', name: 'Provenance Chain & Digital Twin', description: 'Provenance registry prototype for verification workflows and future digital-twin support.', tier: 'Industry-First', category: 'Security', status: 'beta', path: '/provenance', icon: 'Link2', phase: 72, keywords: ['provenance', 'blockchain', 'nft', 'twin', 'verify'] },
  { id: 'live-breaks', name: 'Live Break Room & Auction AI', description: 'Live-break and auction workflow concept staged for future marketplace integrations.', tier: 'Industry-First', category: 'Trading', status: 'live', path: '/live-breaks', icon: 'Tv', phase: 73, keywords: ['break', 'live', 'auction', 'snipe', 'ev'] },

  // ─── Bloomberg-Grade (cross-cutting capabilities) ───────
  { id: 'portfolio-audit', name: 'Portfolio Audit Engine', description: 'Comprehensive portfolio analysis with ROI, diversification, and risk metrics.', tier: 'Bloomberg-Grade', category: 'Analytics', status: 'live', path: '/audit', icon: 'FileSearch', phase: 12, keywords: ['audit', 'portfolio', 'analysis', 'risk'] },
  { id: 'teams', name: 'Team Analytics', description: 'Team-level performance tracking with offense, defense, and form indicators.', tier: 'Bloomberg-Grade', category: 'Data', status: 'live', path: '/teams', icon: 'Target', phase: 12, keywords: ['team', 'analytics', 'offense', 'defense'] },
  { id: 'games', name: 'Game Intelligence', description: 'Live game tracking with impact scoring, key matchups, and swing factors.', tier: 'Bloomberg-Grade', category: 'Data', status: 'live', path: '/games', icon: 'Activity', phase: 12, keywords: ['game', 'live', 'matchup', 'score'] },
  { id: 'trends', name: 'Market Trends', description: 'Multi-dimensional trend analysis across sports, eras, and card categories.', tier: 'Bloomberg-Grade', category: 'Analytics', status: 'live', path: '/trends', icon: 'TrendingUp', phase: 12, keywords: ['trend', 'market', 'movement'] },
  { id: 'compare', name: 'Comparative Analysis', description: 'Side-by-side card and player comparison with performance overlays.', tier: 'Bloomberg-Grade', category: 'Analytics', status: 'live', path: '/compare', icon: 'GitCompare', phase: 12, keywords: ['compare', 'side by side', 'overlay'] },
  { id: 'war-room', name: 'Analyst War Room', description: 'Professional-grade analysis workspace with multi-panel layouts.', tier: 'Bloomberg-Grade', category: 'Analytics', status: 'live', path: '/war-room', icon: 'MonitorDot', phase: 19, keywords: ['war room', 'analyst', 'terminal', 'workspace'] },
  { id: 'portfolio-builder', name: 'Portfolio Builder', description: 'Visual portfolio construction with drag-and-drop grouping and allocation.', tier: 'Bloomberg-Grade', category: 'Portfolio', status: 'live', path: '/builder', icon: 'Kanban', phase: 12, keywords: ['builder', 'construct', 'allocate', 'group'] },
  { id: 'market-ticker', name: 'Market Ticker', description: 'Real-time scrolling market data ticker in the header.', tier: 'Bloomberg-Grade', category: 'UX', status: 'live', path: null, icon: 'Activity', phase: 12, keywords: ['ticker', 'scroll', 'real-time', 'header'] },
  { id: 'prospect-trends', name: 'Prospect Trends', description: 'MiLB prospect trend scoring with breakout probability and 7-day history.', tier: 'Bloomberg-Grade', category: 'Data', status: 'live', path: '/prospects', icon: 'TrendingUp', phase: 12, keywords: ['prospect', 'milb', 'trend', 'breakout'] },
  { id: 'public-portfolio', name: 'Public Portfolio', description: 'Shareable public portfolio pages with customizable display.', tier: 'Bloomberg-Grade', category: 'Social', status: 'live', path: null, icon: 'Globe', phase: 30, keywords: ['public', 'portfolio', 'share', 'profile'] },
  { id: 'leaderboard', name: 'Collector Leaderboard', description: 'Competitive rankings by ROI, portfolio value, and alpha score.', tier: 'Bloomberg-Grade', category: 'Social', status: 'live', path: '/leaderboard', icon: 'Medal', phase: 42, keywords: ['leaderboard', 'rank', 'top', 'score'] },
  { id: 'morning-briefing', name: 'Morning Briefing', description: 'AI-generated daily portfolio briefing with key alerts and recommendations.', tier: 'Bloomberg-Grade', category: 'AI', status: 'live', path: null, icon: 'Newspaper', phase: 63, keywords: ['morning', 'briefing', 'daily', 'summary'] },
  { id: 'ocr-ingestion', name: 'OCR Card Scanner', description: 'Camera-based card scanning with OCR for automatic card identification.', tier: 'Bloomberg-Grade', category: 'AI', status: 'live', path: null, icon: 'Camera', phase: 48, keywords: ['ocr', 'scan', 'camera', 'identify'] },

  // ─── Additional distinct sub-features ───────────────────
  { id: 'sold-vault', name: 'Sold Vault', description: 'Track historical performance of exited positions with realized P/L.', tier: 'Core', category: 'Portfolio', status: 'live', path: '/collection', icon: 'Archive', phase: 2, keywords: ['sold', 'vault', 'history', 'exit'] },
  { id: 'alpha-scanner', name: 'Alpha Scanner', description: 'Vision-based alpha detection overlaying performance stats with price action.', tier: 'Core', category: 'Analytics', status: 'live', path: '/', icon: 'Eye', phase: 12, keywords: ['alpha', 'scanner', 'vision', 'divergence'] },
  { id: 'data-migration', name: 'Data Migration Engine', description: 'Seamless migration from localStorage to Supabase cloud storage.', tier: 'Core', category: 'System', status: 'live', path: null, icon: 'Database', phase: 9, keywords: ['migration', 'cloud', 'supabase', 'sync'] },
  { id: 'sync-scheduler', name: 'Automated Sync Scheduler', description: 'Background portfolio value sync with configurable intervals.', tier: 'Core', category: 'System', status: 'live', path: null, icon: 'RefreshCw', phase: 10, keywords: ['sync', 'schedule', 'auto', 'background'] },
  { id: 'investment-tracking', name: 'Investment Tracking Engine', description: 'Professional P/L tracking with realized/unrealized gains across leagues.', tier: 'Bloomberg-Grade', category: 'Finance', status: 'live', path: '/', icon: 'DollarSign', phase: 11, keywords: ['investment', 'pl', 'profit', 'loss', 'tracking'] },
  { id: 'hedge-simulation', name: 'Hedge Simulation Engine', description: 'Full rebalancing simulation with virtual hedge nodes and deployment tracking.', tier: 'Competitive Moat', category: 'Analytics', status: 'live', path: null, icon: 'Shield', phase: 21, keywords: ['hedge', 'simulation', 'rebalance', 'node'] },
  { id: 'ebay-listing-gen', name: 'eBay Listing Generator', description: 'Auto-generate SEO-optimized listing titles and HTML descriptions.', tier: 'Competitive Moat', category: 'Trading', status: 'live', path: null, icon: 'FileEdit', phase: 29, keywords: ['ebay', 'listing', 'title', 'seo', 'html'] },
  { id: 'bulk-operations', name: 'Bulk Collection Operations', description: 'Select-all, bulk delete with undo, JSON export, and sort by 6 fields.', tier: 'Competitive Moat', category: 'UX', status: 'live', path: '/collection', icon: 'CheckSquare', phase: 32, keywords: ['bulk', 'select', 'delete', 'export'] },
  { id: 'command-palette', name: 'Command Palette', description: 'Ctrl+K searchable command launcher with arrow key navigation and ARIA support.', tier: 'Competitive Moat', category: 'UX', status: 'live', path: null, icon: 'Terminal', phase: 32, keywords: ['command', 'palette', 'launcher', 'ctrl k'] },
  { id: 'swipeable-cards', name: 'Swipeable Card Triage', description: 'Touch gesture support for mobile card triage with haptic feedback.', tier: 'Competitive Moat', category: 'UX', status: 'live', path: null, icon: 'Hand', phase: 32, keywords: ['swipe', 'mobile', 'gesture', 'haptic'] },
  { id: 'skeleton-loaders', name: 'Skeleton Loading States', description: 'Professional skeleton loaders for cards, stats, charts, and dashboard views.', tier: 'Competitive Moat', category: 'UX', status: 'live', path: null, icon: 'Loader', phase: 32, keywords: ['skeleton', 'loading', 'placeholder'] },
  { id: 'playbook-templates', name: 'Negotiation Playbooks', description: 'Pre-built and custom negotiation strategies with configurable parameters.', tier: 'Competitive Moat', category: 'Trading', status: 'live', path: null, icon: 'BookOpen', phase: 16, keywords: ['playbook', 'strategy', 'negotiate', 'template'] },
  { id: 'speed-bonus', name: 'Speed Bonus System', description: 'Earn +2% payout on instant sells accepted within 5 minutes.', tier: 'Competitive Moat', category: 'Trading', status: 'live', path: null, icon: 'Timer', phase: 17, keywords: ['speed', 'bonus', 'instant', 'quick'] },
  { id: 'catalyst-detection', name: 'Catalyst Detection', description: 'Automated identification of price catalysts: scarcity, grade premium, timing.', tier: 'Competitive Moat', category: 'Analytics', status: 'live', path: null, icon: 'Flame', phase: 18, keywords: ['catalyst', 'trigger', 'driver', 'signal'] },
  { id: 'agent-thesis', name: 'Agent Investment Thesis', description: '4-agent consensus analysis with dissent detection and confidence scoring.', tier: 'Competitive Moat', category: 'AI', status: 'live', path: null, icon: 'Brain', phase: 19, keywords: ['thesis', 'consensus', 'agent', 'dissent'] },
  { id: 'monthly-challenges', name: 'Monthly Challenges', description: 'Time-limited community objectives with bonus achievement points.', tier: 'Advanced Intelligence', category: 'Social', status: 'live', path: '/leaderboard', icon: 'Flag', phase: 42, keywords: ['challenge', 'monthly', 'objective', 'bonus'] },
  { id: 'decision-journal', name: 'Decision Journal', description: 'Attach notes to portfolio snapshots and review decisions with actual outcomes.', tier: 'Advanced Intelligence', category: 'Tools', status: 'live', path: null, icon: 'NotebookPen', phase: 45, keywords: ['journal', 'decision', 'notes', 'review'] },
  { id: 'frontier-lab', name: 'Frontier Lab', description: 'Production roadmap for ten differentiated features the market does not currently offer.', tier: 'Competitive Moat', category: 'Strategy', status: 'live', path: '/frontier-lab', icon: 'Sparkles', phase: 148, keywords: ['frontier', 'moat', 'roadmap', 'innovation'] },
  { id: 'restoration-risk-ledger', name: 'Restoration Risk Ledger', description: 'Underwrite trimming, recoloring, cleaning, and restoration risk with evidence-backed discount curves.', tier: 'Competitive Moat', category: 'Risk', status: 'live', path: '/frontier-lab?feature=restoration-risk-ledger', icon: 'ShieldAlert', phase: 149, keywords: ['restoration', 'altered', 'risk', 'forensics'] },
  { id: 'claims-recovery-studio', name: 'Claims Recovery Studio', description: 'Generate insurer-ready incident and recovery packets from valuation, policy, and provenance data.', tier: 'Competitive Moat', category: 'Operations', status: 'live', path: '/frontier-lab?feature=claims-recovery-studio', icon: 'FileCheck', phase: 150, keywords: ['claims', 'insurance', 'recovery', 'incident'] },
  { id: 'venue-failure-drill', name: 'Venue Failure Drill', description: 'Stress test marketplace, vault, and consignment outages as operational portfolio risk.', tier: 'Industry-First', category: 'Risk', status: 'live', path: '/frontier-lab?feature=venue-failure-drill', icon: 'Siren', phase: 151, keywords: ['venue', 'failure', 'drill', 'outage'] },
  { id: 'opportunity-crowding-index', name: 'Opportunity Crowding Index', description: 'Measure whether a collectible thesis is already too crowded to still be alpha.', tier: 'Competitive Moat', category: 'Strategy', status: 'live', path: '/frontier-lab?feature=opportunity-crowding-index', icon: 'Users', phase: 152, keywords: ['crowding', 'consensus', 'alpha', 'hype'] },
  { id: 'provenance-gap-heatmap', name: 'Provenance Gap Heatmap', description: 'Score missing custody windows and prioritize which evidence gaps matter most to value.', tier: 'Industry-First', category: 'Trust', status: 'live', path: '/frontier-lab?feature=provenance-gap-heatmap', icon: 'Map', phase: 153, keywords: ['provenance', 'gap', 'timeline', 'evidence'] },
  { id: 'museum-loan-desk', name: 'Museum Loan Desk', description: 'Operationalize exhibition-grade loans with custody controls, loan fees, and condition tracking.', tier: 'Industry-First', category: 'Operations', status: 'live', path: '/frontier-lab?feature=museum-loan-desk', icon: 'Landmark', phase: 154, keywords: ['museum', 'loan', 'exhibit', 'custody'] },
  { id: 'counterfeit-cluster-radar', name: 'Counterfeit Cluster Radar', description: 'Detect organized fake-card networks by linking listings, serials, imagery, and dispute history.', tier: 'Competitive Moat', category: 'Trust', status: 'live', path: '/frontier-lab?feature=counterfeit-cluster-radar', icon: 'Radar', phase: 155, keywords: ['counterfeit', 'cluster', 'fraud', 'graph'] },
  { id: 'capital-stack-optimizer', name: 'Capital Stack Optimizer', description: 'Compare full sales, partial exits, consignments, and advances against liquidity and tax friction.', tier: 'Competitive Moat', category: 'Finance', status: 'live', path: '/frontier-lab?feature=capital-stack-optimizer', icon: 'Scale', phase: 156, keywords: ['capital stack', 'advance', 'consignment', 'liquidity'] },
  { id: 'prestige-spillover-engine', name: 'Prestige Spillover Engine', description: 'Track how luxury and cultural attention spills into card demand before comps fully move.', tier: 'Industry-First', category: 'Market Structure', status: 'live', path: '/frontier-lab?feature=prestige-spillover-engine', icon: 'Globe', phase: 157, keywords: ['spillover', 'prestige', 'culture', 'cross hobby'] },
  { id: 'reacquisition-radar', name: 'Reacquisition Radar', description: 'Surface disciplined buy-back opportunities for assets you already sold.', tier: 'Competitive Moat', category: 'Strategy', status: 'live', path: '/frontier-lab?feature=reacquisition-radar', icon: 'RotateCcw', phase: 158, keywords: ['reacquisition', 'buyback', 'sold vault', 're-entry'] },

  // ─── v5.0: Next-Gen Investment Intelligence (Phases 159-178) ───
  { id: 'card-genome-sequencer', name: 'Card Genome Sequencer', description: 'DNA-level card fingerprinting with 18 gene categories across Physical, Visual, Chemical, and Rarity dimensions.', tier: 'Industry-First', category: 'Analytics', status: 'live', path: '/card-genome-sequencer', icon: 'Dna', phase: 159, keywords: ['genome', 'dna', 'fingerprint', 'gene', 'physical', 'visual', 'chemical', 'rarity'] },
  { id: 'injury-oracle', name: 'Injury Oracle', description: 'AI-powered player injury forecasting with card value impact modeling across 30+ players.', tier: 'Industry-First', category: 'AI', status: 'live', path: '/injury-oracle', icon: 'HeartPulse', phase: 160, keywords: ['injury', 'oracle', 'forecast', 'health', 'impact', 'player'] },
  { id: 'cross-asset-correlation-v2', name: 'Cross-Asset Correlation', description: 'Correlates card values with S&P 500, Bitcoin, gold, real estate, and treasuries.', tier: 'Differentiated', category: 'Analytics', status: 'live', path: '/cross-asset-correlation', icon: 'GitMerge', phase: 161, keywords: ['cross asset', 'correlation', 'sp500', 'bitcoin', 'gold', 'real estate', 'treasuries'] },
  { id: 'collector-social-graph', name: 'Collector Social Graph', description: 'Network analysis mapping collector influence, herd behavior, and trend adoption.', tier: 'Industry-First', category: 'Social', status: 'live', path: '/collector-social-graph', icon: 'Network', phase: 162, keywords: ['social graph', 'network', 'influence', 'herd', 'trend', 'collector'] },
  { id: 'restoration-simulator', name: 'Restoration Simulator', description: 'AI card restoration/regrading simulation with ROI analysis.', tier: 'Differentiated', category: 'Tools', status: 'live', path: '/restoration-simulator', icon: 'Wrench', phase: 163, keywords: ['restoration', 'regrade', 'simulation', 'roi', 'condition'] },
  { id: 'market-maker-arena', name: 'Market Maker Arena', description: 'Competing AI trading bot strategies with live P&L and order books.', tier: 'Industry-First', category: 'Trading', status: 'live', path: '/market-maker-arena', icon: 'Swords', phase: 164, keywords: ['market maker', 'bot', 'trading', 'pnl', 'order book', 'arena'] },
  { id: 'fractional-vault-v2', name: 'Fractional Vault', description: 'Tokenized fractional ownership concept with governance modeling; beta until legal, securities, and execution rails are complete.', tier: 'Industry-First', category: 'Trading', status: 'beta', path: '/fractional-vault', icon: 'Landmark', phase: 165, keywords: ['fractional', 'vault', 'tokenized', 'ownership', 'governance', 'shares'] },
  { id: 'portfolio-stress-tester', name: 'Portfolio Stress Tester', description: 'Monte Carlo simulation and VaR analysis for card portfolios.', tier: 'Differentiated', category: 'Analytics', status: 'live', path: '/portfolio-stress-tester', icon: 'FlaskConical', phase: 166, keywords: ['stress test', 'monte carlo', 'var', 'simulation', 'risk'] },
  { id: 'rookie-pipeline-scanner', name: 'Rookie Pipeline Scanner', description: 'Pre-draft prospect scouting with projected card values.', tier: 'Advanced Intelligence', category: 'Data', status: 'live', path: '/rookie-pipeline-scanner', icon: 'Binoculars', phase: 167, keywords: ['rookie', 'pipeline', 'prospect', 'draft', 'scouting', 'projected'] },
  { id: 'forensics-lab', name: 'Forensics Lab', description: '10-layer forensic authentication and counterfeit detection.', tier: 'Industry-First', category: 'Security', status: 'live', path: '/forensics-lab', icon: 'Microscope', phase: 168, keywords: ['forensics', 'authentication', 'counterfeit', 'detection', 'layers'] },
  { id: 'card-decay-predictor', name: 'Card Decay Predictor', description: 'Physics-based condition degradation modeling with half-life predictions.', tier: 'Differentiated', category: 'Analytics', status: 'live', path: '/card-decay-predictor', icon: 'Hourglass', phase: 169, keywords: ['decay', 'degradation', 'condition', 'half-life', 'physics', 'aging'] },
  { id: 'narrative-arc-engine', name: 'Narrative Arc Engine', description: 'Player career story-driven card valuation and premium quantification.', tier: 'Industry-First', category: 'Analytics', status: 'live', path: '/narrative-arc-engine', icon: 'BookOpen', phase: 170, keywords: ['narrative', 'arc', 'career', 'story', 'valuation', 'premium'] },
  { id: 'liquidity-depth-scanner', name: 'Liquidity Depth Scanner', description: 'Market depth analysis with exit strategy planning.', tier: 'Differentiated', category: 'Analytics', status: 'live', path: '/liquidity-depth-scanner', icon: 'Layers', phase: 171, keywords: ['liquidity', 'depth', 'market', 'exit', 'strategy'] },
  { id: 'contagion-mapper', name: 'Contagion Mapper', description: 'Systemic risk propagation modeling across card portfolios.', tier: 'Industry-First', category: 'Risk', status: 'live', path: '/contagion-mapper', icon: 'GitFork', phase: 172, keywords: ['contagion', 'systemic', 'risk', 'propagation', 'cascade'] },
  { id: 'grail-index-constructor', name: 'Grail Index Constructor', description: 'Build custom investable card indices with rebalancing.', tier: 'Differentiated', category: 'Portfolio', status: 'live', path: '/grail-index-constructor', icon: 'Crown', phase: 173, keywords: ['grail', 'index', 'custom', 'investable', 'rebalancing'] },
  { id: 'print-run-decoder', name: 'Print Run Decoder', description: 'Reverse-engineer hidden print runs from population data.', tier: 'Industry-First', category: 'Data', status: 'live', path: '/print-run-decoder', icon: 'Binary', phase: 174, keywords: ['print run', 'decode', 'population', 'reverse engineer', 'hidden'] },
  { id: 'temporal-arbitrage-radar', name: 'Temporal Arbitrage Radar', description: 'Time-based pricing anomaly detection across events and seasons.', tier: 'Differentiated', category: 'Trading', status: 'live', path: '/temporal-arbitrage-radar', icon: 'Clock', phase: 175, keywords: ['temporal', 'arbitrage', 'pricing', 'anomaly', 'seasonal', 'events'] },
  { id: 'collection-dna-mixer', name: 'Collection DNA Mixer', description: 'Genetic algorithm collection breeding for optimal hybrid portfolios.', tier: 'Industry-First', category: 'AI', status: 'live', path: '/collection-dna-mixer', icon: 'Combine', phase: 176, keywords: ['dna', 'mixer', 'genetic', 'algorithm', 'breeding', 'hybrid', 'portfolio'] },
  { id: 'card-yield-farming', name: 'Card Yield Farming', description: 'Passive income from card lending, licensing, staking, and insurance.', tier: 'Industry-First', category: 'Finance', status: 'live', path: '/card-yield-farming', icon: 'Sprout', phase: 177, keywords: ['yield', 'farming', 'lending', 'licensing', 'staking', 'passive income'] },
  { id: 'chaos-theory-simulator', name: 'Chaos Theory Simulator', description: 'Butterfly effect modeling for card market cascades.', tier: 'Industry-First', category: 'Analytics', status: 'live', path: '/chaos-theory-simulator', icon: 'Orbit', phase: 178, keywords: ['chaos', 'butterfly', 'cascade', 'theory', 'simulation', 'market'] },
  // v6.0: Industry-Absent Innovation Suite
  { id: 'injury-shockwave', name: 'Injury Shockwave Engine', description: 'Real-time injury impact propagation across player networks with cascade modeling.', tier: 'Industry-First', category: 'Analytics', status: 'live', path: '/injury-shockwave', icon: 'Zap', phase: 200, keywords: ['injury', 'shockwave', 'cascade', 'propagation', 'impact', 'health', 'ripple'] },
  { id: 'ar-vault-walkthrough', name: 'AR Vault Walkthrough', description: 'Immersive 3D card showcases with live price overlays and virtual tours.', tier: 'Industry-First', category: 'Social', status: 'live', path: '/ar-vault-walkthrough', icon: 'Eye', phase: 201, keywords: ['ar', 'vault', 'walkthrough', '3d', 'showcase', 'virtual', 'tour', 'display'] },
  { id: 'hof-probability', name: 'HOF Probability Engine', description: 'Career trajectory analysis with Hall of Fame probability and premium pricing models.', tier: 'Industry-First', category: 'Analytics', status: 'live', path: '/hof-probability', icon: 'Award', phase: 202, keywords: ['hof', 'hall of fame', 'probability', 'career', 'trajectory', 'premium', 'pricing'] },
  { id: 'market-microstructure', name: 'Market Microstructure', description: 'Level 2 order flow analytics, bid-ask spreads, and market depth visualization.', tier: 'Industry-First', category: 'Trading', status: 'live', path: '/market-microstructure', icon: 'BarChart3', phase: 203, keywords: ['microstructure', 'order flow', 'bid', 'ask', 'spread', 'depth', 'level 2', 'institutional'] },
  { id: 'iot-condition-guardian', name: 'IoT Condition Guardian', description: 'Smart sensor monitoring for card storage with temperature, humidity, and UV alerts.', tier: 'Industry-First', category: 'Security', status: 'live', path: '/iot-condition-guardian', icon: 'Thermometer', phase: 204, keywords: ['iot', 'sensor', 'temperature', 'humidity', 'uv', 'storage', 'condition', 'guardian'] },
  { id: 'fractional-syndicate', name: 'Fractional Syndicate Engine', description: 'Pooled capital investment vehicles with democratic governance and K-1 generation.', tier: 'Industry-First', category: 'Finance', status: 'live', path: '/fractional-syndicate', icon: 'Users', phase: 205, keywords: ['syndicate', 'fractional', 'governance', 'pooled', 'capital', 'voting', 'k-1'] },
  { id: 'voice-card-show', name: 'Voice Card Show Companion', description: 'Hands-free AI assistant for live card show negotiations with vendor scoring.', tier: 'Industry-First', category: 'Tools', status: 'live', path: '/voice-card-show', icon: 'Mic', phase: 206, keywords: ['voice', 'card show', 'companion', 'negotiation', 'vendor', 'hands-free', 'live'] },
  { id: 'narrative-alpha', name: 'Narrative Alpha Detector', description: 'AI-powered narrative detection for early-mover card trading advantage.', tier: 'Industry-First', category: 'AI', status: 'live', path: '/narrative-alpha', icon: 'BookOpen', phase: 207, keywords: ['narrative', 'alpha', 'nlp', 'media', 'sentiment', 'emerging', 'story', 'hype'] },
  { id: 'counterfactual-value', name: 'Counterfactual Value Engine', description: 'Alternate timeline card valuations — explore what could have been.', tier: 'Industry-First', category: 'Analytics', status: 'live', path: '/counterfactual-value', icon: 'GitBranch', phase: 208, keywords: ['counterfactual', 'what if', 'alternate', 'timeline', 'scenario', 'valuation'] },
  { id: 'biometric-trading-guard', name: 'Biometric Trading Guard', description: 'Wearable-powered emotional trading protection with AI coaching.', tier: 'Industry-First', category: 'Risk', status: 'live', path: '/biometric-trading-guard', icon: 'HeartPulse', phase: 209, keywords: ['biometric', 'heart rate', 'hrv', 'stress', 'cooldown', 'emotional', 'trading', 'guard'] },
  // v6.1: Industry-Absent Innovation — Round 2
  { id: 'dopamine-cycle-tracker', name: 'Dopamine Cycle Tracker', description: 'Detect and manage dopamine-driven overconsumption cycles in buying behavior.', tier: 'Industry-First', category: 'Analytics', status: 'live', path: '/dopamine-cycle-tracker', icon: 'Brain', phase: 210, keywords: ['dopamine', 'cycle', 'behavior', 'impulse', 'overconsumption', 'spending'] },
  { id: 'hobby-liquidity-crisis', name: 'Hobby Liquidity Crisis', description: 'Stress-test portfolio survival under hobby-wide liquidity shocks and market freezes.', tier: 'Industry-First', category: 'Risk', status: 'live', path: '/hobby-liquidity-crisis', icon: 'AlertTriangle', phase: 211, keywords: ['liquidity', 'crisis', 'shock', 'freeze', 'stress test', 'survival'] },
  { id: 'memory-index', name: 'Memory Index', description: 'Quantify sentimental and nostalgia value as a tradeable premium layer.', tier: 'Industry-First', category: 'Analytics', status: 'live', path: '/memory-index', icon: 'Sparkles', phase: 212, keywords: ['memory', 'nostalgia', 'sentimental', 'premium', 'emotional', 'index'] },
  { id: 'pop-forecaster', name: 'Pop Forecaster', description: 'Predict future PSA/BGS population counts with grading submission trend modeling.', tier: 'Industry-First', category: 'Analytics', status: 'live', path: '/pop-forecaster', icon: 'TrendingUp', phase: 213, keywords: ['pop', 'population', 'forecast', 'grading', 'submission', 'psa', 'bgs'] },
  { id: 'draft-capital-futures', name: 'Draft Capital Futures', description: 'Trade forward contracts on draft capital value with settlement and margin mechanics.', tier: 'Industry-First', category: 'Trading', status: 'live', path: '/draft-capital-futures', icon: 'Target', phase: 214, keywords: ['draft', 'capital', 'futures', 'forward', 'contract', 'settlement', 'margin'] },
  { id: 'shadow-inventory', name: 'Shadow Inventory', description: 'Detect hidden supply from vault holdings, estate releases, and institutional positions.', tier: 'Industry-First', category: 'Analytics', status: 'live', path: '/shadow-inventory', icon: 'MapPin', phase: 215, keywords: ['shadow', 'inventory', 'hidden', 'supply', 'vault', 'estate', 'institutional'] },
  { id: 'emotion-journal', name: 'Emotion Journal', description: 'Track emotional state around buy/sell decisions with AI pattern recognition.', tier: 'Industry-First', category: 'Tools', status: 'live', path: '/emotion-journal', icon: 'Heart', phase: 216, keywords: ['emotion', 'journal', 'mood', 'sentiment', 'decision', 'psychology'] },
  { id: 'estate-succession', name: 'Estate Succession', description: 'Multi-generational collection transfer planning with tax-optimized succession strategies.', tier: 'Industry-First', category: 'Finance', status: 'live', path: '/estate-succession', icon: 'Landmark', phase: 217, keywords: ['estate', 'succession', 'transfer', 'generational', 'inheritance', 'tax'] },
  { id: 'refractor-mapper', name: 'Refractor Mapper', description: 'Visual mapping and identification of refractor parallels with rarity scoring.', tier: 'Industry-First', category: 'Tools', status: 'live', path: '/refractor-mapper', icon: 'Eye', phase: 218, keywords: ['refractor', 'parallel', 'prizm', 'chrome', 'rarity', 'visual', 'map'] },
  { id: 'centering-analyzer', name: 'Centering Analyzer', description: 'AI-powered card centering measurement with grade impact prediction.', tier: 'Industry-First', category: 'AI', status: 'live', path: '/centering-analyzer', icon: 'Crosshair', phase: 219, keywords: ['centering', 'alignment', 'grade', 'measurement', 'prediction', 'subgrade'] },
  // ─── v7.0: Industry-Absent Innovation — Round 3 (Phases 224-233) ───
  { id: 'regulatory-compliance-radar', name: 'Regulatory Compliance Radar', description: 'Track emerging legislation around collectible securities, sales tax nexus, and AML rules.', tier: 'Industry-First', category: 'Risk', status: 'live', path: '/regulatory-compliance-radar', icon: 'Shield', phase: 224, keywords: ['regulatory', 'compliance', 'tax', 'aml', 'legislation', 'securities', 'nexus'] },
  { id: 'acoustic-authentication', name: 'Acoustic Authentication Engine', description: 'Sound-based micro-tap resonance analysis for detecting trimming and alterations.', tier: 'Industry-First', category: 'Security', status: 'live', path: '/acoustic-authentication', icon: 'Volume2', phase: 225, keywords: ['acoustic', 'authentication', 'sound', 'resonance', 'trimming', 'altered'] },
  { id: 'dealer-flow-intelligence', name: 'Dealer Flow Intelligence', description: 'Wholesale dealer inventory movement tracking and institutional accumulation patterns.', tier: 'Industry-First', category: 'Market Structure', status: 'live', path: '/dealer-flow-intelligence', icon: 'Briefcase', phase: 226, keywords: ['dealer', 'flow', 'wholesale', 'institutional', 'accumulation', 'distribution'] },
  { id: 'psychographic-demand', name: 'Psychographic Demand Modeler', description: 'Buyer demographic cohort modeling and demand prediction by persona.', tier: 'Industry-First', category: 'Analytics', status: 'live', path: '/psychographic-demand', icon: 'Users', phase: 227, keywords: ['psychographic', 'demographic', 'cohort', 'demand', 'persona', 'nostalgia'] },
  { id: 'micro-geographic-demand', name: 'Micro-Geographic Demand Heatmap', description: 'Zip-code level buyer concentration mapping with regional trend analysis.', tier: 'Industry-First', category: 'Analytics', status: 'live', path: '/micro-geographic-demand', icon: 'MapPin', phase: 228, keywords: ['geographic', 'heatmap', 'regional', 'zip code', 'buyer', 'local'] },
  { id: 'cross-hobby-contagion', name: 'Cross-Hobby Contagion Network', description: 'Track trend propagation between Pokemon, sports cards, comics, and memorabilia.', tier: 'Industry-First', category: 'Analytics', status: 'live', path: '/cross-hobby-contagion', icon: 'Network', phase: 229, keywords: ['cross hobby', 'contagion', 'pokemon', 'comics', 'sneakers', 'spillover'] },
  { id: 'venue-health-oracle', name: 'Venue Health Oracle', description: 'Real-time reputation scoring for every marketplace and auction house.', tier: 'Industry-First', category: 'Trust', status: 'live', path: '/venue-health-oracle', icon: 'Building2', phase: 230, keywords: ['venue', 'marketplace', 'reputation', 'score', 'dispute', 'fees'] },
  { id: 'negotiation-replay', name: 'AI Negotiation Replay Theater', description: 'Record, replay, and study negotiation sessions like game film.', tier: 'Industry-First', category: 'Trading', status: 'live', path: '/negotiation-replay', icon: 'PlayCircle', phase: 231, keywords: ['negotiation', 'replay', 'theater', 'tactics', 'strategy', 'game film'] },
  { id: 'card-material-spectrometry', name: 'Card Material Spectrometry', description: 'Spectral analysis simulation for detecting reprints and material variations.', tier: 'Industry-First', category: 'Security', status: 'live', path: '/card-material-spectrometry', icon: 'Microscope', phase: 232, keywords: ['spectrometry', 'spectral', 'material', 'reprint', 'uv', 'ink'] },
  { id: 'generational-demand-forecaster', name: 'Generational Demand Forecaster', description: '10-25 year demographic-driven demand projection modeling.', tier: 'Industry-First', category: 'Analytics', status: 'live', path: '/generational-demand-forecaster', icon: 'Clock', phase: 233, keywords: ['generational', 'forecast', 'demographic', 'wealth transfer', 'nostalgia cycle', 'long term'] },
  // ─── v7.1: Industry-Absent Innovation — Round 4 (Phases 234-253) ───
  { id: 'slab-case-forensics', name: 'Slab Case Forensics', description: 'Analyze PSA/BGS holder authenticity via case dimensions, label fonts, and UV markers.', tier: 'Industry-First', category: 'Security', status: 'live', path: '/slab-case-forensics', icon: 'ScanLine', phase: 234, keywords: ['slab', 'case', 'forensics', 'holder', 'label', 'uv', 'psa', 'bgs'] },
  { id: 'price-whisperer', name: 'AI Price Whisperer', description: 'Natural language price queries with AI-powered fair market value analysis.', tier: 'Industry-First', category: 'AI', status: 'live', path: '/price-whisperer', icon: 'MessageSquare', phase: 235, keywords: ['price', 'whisperer', 'fair value', 'natural language', 'query', 'comps'] },
  { id: 'card-loan-collateral', name: 'Card Loan Collateral Engine', description: 'Use graded cards as collateral for hobby lending with LTV ratios.', tier: 'Industry-First', category: 'Finance', status: 'live', path: '/card-loan-collateral', icon: 'Landmark', phase: 236, keywords: ['loan', 'collateral', 'ltv', 'lending', 'borrow', 'credit'] },
  { id: 'grading-arbitrage', name: 'Grading Company Arbitrage', description: 'Cross-grading company price differentials between PSA, BGS, and SGC.', tier: 'Industry-First', category: 'Trading', status: 'live', path: '/grading-arbitrage', icon: 'ArrowLeftRight', phase: 237, keywords: ['grading', 'arbitrage', 'crossover', 'psa', 'bgs', 'sgc', 'premium'] },
  { id: 'consignment-optimizer', name: 'Consignment Fee Optimizer', description: 'Compare fees across PWCC, Goldin, Heritage, and eBay for optimal sale route.', tier: 'Industry-First', category: 'Trading', status: 'live', path: '/consignment-optimizer', icon: 'Scale', phase: 238, keywords: ['consignment', 'fees', 'optimizer', 'pwcc', 'goldin', 'heritage', 'route'] },
  { id: 'card-aging-clock', name: 'Card DNA Aging Clock', description: 'Estimate actual card age from material degradation signatures.', tier: 'Industry-First', category: 'Security', status: 'live', path: '/card-aging-clock', icon: 'Clock', phase: 239, keywords: ['aging', 'clock', 'degradation', 'material', 'age', 'verification'] },
  { id: 'sentiment-seismograph', name: 'Hobby Sentiment Seismograph', description: 'Real-time social media and forum sentiment monitoring with spike alerts.', tier: 'Industry-First', category: 'Analytics', status: 'live', path: '/sentiment-seismograph', icon: 'Activity', phase: 240, keywords: ['sentiment', 'seismograph', 'social', 'twitter', 'reddit', 'forum', 'alert'] },
  { id: 'contract-valuation', name: 'Player Contract Valuation', description: 'Map player contract status to card price impact windows.', tier: 'Industry-First', category: 'Data', status: 'live', path: '/contract-valuation', icon: 'FileCheck', phase: 241, keywords: ['contract', 'valuation', 'free agency', 'extension', 'trade', 'impact'] },
  { id: 'collection-entropy', name: 'Collection Entropy Score', description: 'Measure portfolio randomness vs intentional strategy alignment.', tier: 'Industry-First', category: 'Analytics', status: 'live', path: '/collection-entropy', icon: 'Dices', phase: 242, keywords: ['entropy', 'randomness', 'strategy', 'intentionality', 'concentration'] },
  { id: 'card-show-navigator', name: 'Card Show GPS Navigator', description: 'Floor plan optimization for card shows with dealer routing.', tier: 'Industry-First', category: 'Tools', status: 'live', path: '/card-show-navigator', icon: 'MapPin', phase: 243, keywords: ['card show', 'navigator', 'floor plan', 'routing', 'dealer', 'booth'] },
  { id: 'influencer-quantifier', name: 'Influencer Impact Quantifier', description: 'Measure exactly how much specific influencer posts move card prices.', tier: 'Industry-First', category: 'Analytics', status: 'live', path: '/influencer-quantifier', icon: 'Megaphone', phase: 244, keywords: ['influencer', 'impact', 'youtube', 'twitter', 'price move', 'quantify'] },
  { id: 'wax-ct-scanner', name: 'Sealed Wax CT Scanner', description: 'Non-invasive pack/box hot pack detection via weight and density analysis.', tier: 'Industry-First', category: 'Tools', status: 'live', path: '/wax-ct-scanner', icon: 'Box', phase: 245, keywords: ['wax', 'ct', 'scanner', 'hot pack', 'weight', 'density', 'sealed'] },
  { id: 'manipulation-detector', name: 'Market Manipulation Detector', description: 'Identify wash trading, shill bidding, and price painting patterns.', tier: 'Industry-First', category: 'Risk', status: 'live', path: '/manipulation-detector', icon: 'AlertTriangle', phase: 246, keywords: ['manipulation', 'wash trade', 'shill', 'bid', 'price paint', 'fraud'] },
  { id: 'insurance-claims-ai', name: 'Card Insurance Claims AI', description: 'AI-assisted insurance claim filing with automated damage assessment.', tier: 'Industry-First', category: 'Finance', status: 'live', path: '/insurance-claims-ai', icon: 'Shield', phase: 247, keywords: ['insurance', 'claims', 'damage', 'assessment', 'filing', 'recovery'] },
  { id: 'recession-playbook', name: 'Hobby Recession Playbook', description: 'Pre-built strategies for different economic downturn scenarios.', tier: 'Industry-First', category: 'Strategy', status: 'live', path: '/recession-playbook', icon: 'BookOpen', phase: 248, keywords: ['recession', 'playbook', 'economic', 'downturn', 'strategy', 'defensive'] },
  { id: 'personality-matrix', name: 'Collector Personality Matrix', description: 'MBTI-style collector profiling with strategy alignment recommendations.', tier: 'Industry-First', category: 'Tools', status: 'live', path: '/personality-matrix', icon: 'Users', phase: 249, keywords: ['personality', 'matrix', 'profile', 'mbti', 'collector type', 'strategy'] },
  { id: 'photo-studio', name: 'Card Photography Studio', description: 'AI-enhanced card photography with listing-ready templates.', tier: 'Industry-First', category: 'Tools', status: 'live', path: '/photo-studio', icon: 'Camera', phase: 250, keywords: ['photo', 'studio', 'photography', 'listing', 'template', 'enhance'] },
  { id: 'peer-lending', name: 'Peer Lending Marketplace', description: 'Collector-to-collector card lending with insurance coverage.', tier: 'Industry-First', category: 'Trading', status: 'live', path: '/peer-lending', icon: 'ArrowLeftRight', phase: 251, keywords: ['peer', 'lending', 'borrow', 'loan', 'marketplace', 'insurance'] },
  { id: 'draft-night-tracker', name: 'Draft Night Live Tracker', description: 'Real-time card price reactions during live draft events.', tier: 'Industry-First', category: 'Data', status: 'live', path: '/draft-night-tracker', icon: 'Zap', phase: 252, keywords: ['draft', 'night', 'live', 'tracker', 'price', 'reaction', 'pick'] },
  { id: 'vintage-provenance', name: 'Vintage Provenance Timeline', description: 'Chain of custody reconstruction for pre-1970 cards with verification.', tier: 'Industry-First', category: 'Security', status: 'live', path: '/vintage-provenance', icon: 'History', phase: 253, keywords: ['vintage', 'provenance', 'timeline', 'custody', 'chain', 'pre-war'] },
  // Coming-soon features now live
  { id: 'what-if-simulator', name: 'What-If Simulator', description: 'Trade-scenario planning workspace for NAV and diversification impact analysis.', tier: 'Competitive Moat', category: 'Analytics', status: 'live', path: '/what-if-simulator', icon: 'FlaskConical', phase: 220, keywords: ['simulate', 'what if', 'trade', 'test', 'scenario', 'nav'] },
  { id: 'grading-batch-planner', name: 'Grading Batch Planner', description: 'Batch grading planner with expected ROI, submission tiers, and cost optimization.', tier: 'Competitive Moat', category: 'Tools', status: 'live', path: '/grading-batch-planner', icon: 'ClipboardList', phase: 221, keywords: ['grading', 'batch', 'submission', 'roi', 'planner'] },
  { id: 'ebay-listing-generator', name: 'eBay Listing Generator', description: 'SEO-optimized eBay listing generation with title builder and HTML templates.', tier: 'Competitive Moat', category: 'Trading', status: 'live', path: '/ebay-listing-generator', icon: 'ShoppingBag', phase: 222, keywords: ['ebay', 'listing', 'sell', 'seo', 'title', 'html'] },
  { id: 'wax-break-roi-tracker', name: 'Wax Break ROI Tracker', description: 'Track ROI from sealed wax breaks with hit logging, EV analysis, and break history.', tier: 'Competitive Moat', category: 'Tools', status: 'live', path: '/wax-break-roi-tracker', icon: 'Package', phase: 223, keywords: ['wax', 'break', 'box', 'roi', 'sealed', 'hit', 'ev'] },

  // ─── v8.0: Industry-Absent Innovation — Frontier Phase (Phases 254-263) ─────
  { id: 'auction-equilibrium', name: 'Auction Game Theory Engine', description: 'Bayesian Nash equilibrium bidding with opponent modeling, exploitability scoring, and optimal bid timing across Goldin, Heritage, Whatnot, and eBay.', tier: 'Industry-First', category: 'Trading', status: 'live', path: '/auction-equilibrium', icon: 'Gavel', phase: 254, keywords: ['auction', 'game theory', 'nash', 'equilibrium', 'bidding', 'exploit', 'goldin', 'heritage', 'bayesian'] },
  { id: 'memetic-propagation', name: 'Memetic Propagation Tracker', description: 'SIR epidemiological models applied to card market narratives — track R₀, viral load, patient zero, and contagion trees for price-moving narratives.', tier: 'Industry-First', category: 'AI', status: 'live', path: '/memetic-propagation', icon: 'Radio', phase: 255, keywords: ['memetic', 'narrative', 'propagation', 'viral', 'contagion', 'SIR', 'epidemiology', 'hype', 'spread'] },
  { id: 'circadian-optimizer', name: 'Circadian Market Rhythm Optimizer', description: 'Chronoeconomic analysis of time-of-day, day-of-week, and seasonal biological rhythms to optimize every transaction timing.', tier: 'Industry-First', category: 'Market Structure', status: 'live', path: '/circadian-optimizer', icon: 'Clock', phase: 256, keywords: ['circadian', 'timing', 'rhythm', 'chronoeconomic', 'optimal', 'when to buy', 'when to sell', 'market clock'] },
  { id: 'cultural-velocity', name: 'Cultural Velocity Tracker', description: 'Track how cultural moments — movies, music, social media events — create price shocks across the card market with velocity scoring.', tier: 'Industry-First', category: 'AI', status: 'live', path: '/cultural-velocity', icon: 'Zap', phase: 257, keywords: ['cultural', 'velocity', 'catalyst', 'movie', 'documentary', 'social media', 'price shock', 'trend'] },
  { id: 'counterparty-fingerprint', name: 'Counterparty Behavioral Fingerprinting', description: 'Cognitive bias profiling of buyers and sellers — infer loss aversion, anchoring, endowment effect from transaction patterns for negotiation advantage.', tier: 'Industry-First', category: 'Trading', status: 'live', path: '/counterparty-fingerprint', icon: 'Fingerprint', phase: 258, keywords: ['counterparty', 'behavioral', 'fingerprint', 'bias', 'negotiation', 'psychology', 'archetype', 'profiling'] },
  { id: 'collection-topology', name: 'Collection Topology Mapper', description: 'Persistent homology and Betti number analysis revealing structural gaps, liquidity deserts, and resilience vulnerabilities invisible to traditional metrics.', tier: 'Industry-First', category: 'Portfolio', status: 'live', path: '/collection-topology', icon: 'Hexagon', phase: 259, keywords: ['topology', 'homology', 'betti', 'structural', 'gap', 'resilience', 'cluster', 'mathematical'] },
  { id: 'survivorship-bias', name: 'Survivorship Bias Corrector', description: 'See the FULL distribution including crashed, delisted, and disappeared cards — corrects the hidden bias in visible market comps.', tier: 'Industry-First', category: 'Analytics', status: 'live', path: '/survivorship-bias', icon: 'EyeOff', phase: 260, keywords: ['survivorship', 'bias', 'corrector', 'hidden', 'delisted', 'crashed', 'true median', 'overvaluation'] },
  { id: 'forgery-evolution', name: 'Forgery Evolution Network', description: 'Track how counterfeiting techniques evolve and spread — detection difficulty scoring, evolution timelines, and targeted card alerts.', tier: 'Industry-First', category: 'Security', status: 'live', path: '/forgery-evolution', icon: 'Shield', phase: 261, keywords: ['forgery', 'counterfeit', 'fake', 'evolution', 'detection', 'threat', 'trimming', 'label swap'] },
  { id: 'decision-fatigue', name: 'Decision Fatigue Guardian', description: 'Cognitive load monitoring with real-time energy tracking, quality degradation detection, and progressive intervention system.', tier: 'Industry-First', category: 'Risk', status: 'live', path: '/decision-fatigue', icon: 'Brain', phase: 262, keywords: ['decision', 'fatigue', 'cognitive', 'load', 'energy', 'quality', 'intervention', 'cooldown', 'guardian'] },
  { id: 'opportunity-cost-phantom', name: 'Opportunity Cost Phantom Portfolio', description: 'Track the road not taken — every viewed, bid-on, or passed card builds a phantom portfolio revealing regret-adjusted alpha and behavioral gaps.', tier: 'Industry-First', category: 'Analytics', status: 'live', path: '/opportunity-cost-phantom', icon: 'Ghost', phase: 263, keywords: ['opportunity', 'cost', 'phantom', 'regret', 'missed', 'bullet dodged', 'road not taken', 'counterfactual'] },

  // v9.0: Industry Phases — Group & Enterprise Scale (Phases 264-273)
  { id: 'shared-watchlists', name: 'Shared Watchlists & Collaborative Research', description: 'Multi-user watchlists with real-time collaboration, shared notes, consensus signals, and group research threads.', tier: 'Industry-First', category: 'Social', status: 'live', path: '/shared-watchlists', icon: 'Eye', phase: 264, keywords: ['shared', 'watchlist', 'collaborative', 'research', 'consensus', 'notes', 'group'] },
  { id: 'group-breaks', name: 'Group Break Planning & Cost Splitting', description: 'Organize group breaks with automated cost splitting, slot management, hit tracking, ROI analysis, and break history.', tier: 'Industry-First', category: 'Social', status: 'live', path: '/group-breaks', icon: 'Package', phase: 265, keywords: ['group', 'break', 'wax', 'split', 'cost', 'slot', 'hit', 'random team'] },
  { id: 'club-management', name: 'Club & Guild Management', description: 'Create and manage collector clubs with shared goals, treasury management, member hierarchy, and club-level analytics.', tier: 'Industry-First', category: 'Social', status: 'live', path: '/club-management', icon: 'Crown', phase: 266, keywords: ['club', 'guild', 'group', 'treasury', 'goals', 'members', 'community'] },
  { id: 'collective-grading', name: 'Collective Grading Submissions', description: 'Pool grading submissions across collectors for volume discounts, shared shipping costs, and negotiated turnaround times.', tier: 'Industry-First', category: 'Social', status: 'live', path: '/collective-grading', icon: 'Award', phase: 267, keywords: ['collective', 'grading', 'pool', 'volume', 'discount', 'submission', 'PSA', 'BGS'] },
  { id: 'shared-dashboards', name: 'Shared Analytics Dashboards', description: 'Collaborative dashboards with shared widgets, KPIs, real-time group metrics, comments, and dashboard templates.', tier: 'Industry-First', category: 'Social', status: 'live', path: '/shared-dashboards', icon: 'LayoutDashboard', phase: 268, keywords: ['shared', 'dashboard', 'collaborative', 'widgets', 'KPI', 'analytics', 'template'] },
  { id: 'rbac-teams', name: 'Role-Based Access Control & Teams', description: 'Enterprise-grade team management with granular permissions, MFA enforcement, IP restrictions, and security audit logging.', tier: 'Industry-First', category: 'System', status: 'live', path: '/rbac-teams', icon: 'Shield', phase: 269, keywords: ['rbac', 'roles', 'permissions', 'teams', 'access', 'control', 'security', 'MFA'] },
  { id: 'white-label-api', name: 'White-Label & API Access', description: 'Enterprise API management with key provisioning, rate limiting, webhook configuration, usage analytics, and white-label instances.', tier: 'Industry-First', category: 'System', status: 'live', path: '/white-label-api', icon: 'Code', phase: 270, keywords: ['api', 'white-label', 'webhook', 'rate limit', 'key', 'endpoint', 'integration'] },
  { id: 'dealer-inventory', name: 'Dealer Inventory Management', description: 'Enterprise-grade dealer inventory with bulk operations, multi-venue listing management, turnover analytics, and consignment tracking.', tier: 'Industry-First', category: 'Operations', status: 'live', path: '/dealer-inventory', icon: 'Store', phase: 271, keywords: ['dealer', 'inventory', 'bulk', 'venue', 'listing', 'turnover', 'wholesale'] },
  { id: 'fund-reporting', name: 'Fund Reporting & LP Letters', description: 'Institutional fund reporting with NAV calculations, performance attribution, LP letters, K-1 generation, and investor relations.', tier: 'Industry-First', category: 'Finance', status: 'live', path: '/fund-reporting', icon: 'Building2', phase: 272, keywords: ['fund', 'LP', 'letter', 'NAV', 'attribution', 'K-1', 'investor', 'institutional'] },
  { id: 'audit-trail', name: 'Audit Trail & Compliance Logging', description: 'Immutable audit trail with compliance dashboards, regulatory reporting, data retention policies, and OFAC/AML screening.', tier: 'Industry-First', category: 'Operations', status: 'live', path: '/audit-trail', icon: 'ScrollText', phase: 273, keywords: ['audit', 'trail', 'compliance', 'logging', 'regulatory', 'AML', 'OFAC', 'retention'] },

  // v10.0: Group Scale Phase 2 — Community Infrastructure (Phases 274-283)
  { id: 'collaborative-set-registry', name: 'Collaborative Set Registry', description: 'Multi-collector set building coordination with gap analysis, contribution scoring, and milestone tracking across master sets.', tier: 'Industry-First', category: 'Social', status: 'live', path: '/collaborative-set-registry', icon: 'Puzzle', phase: 274, keywords: ['set', 'registry', 'collaborative', 'master', 'complete', 'gap', 'checklist', 'build'] },
  { id: 'card-show-squad', name: 'Card Show Squad Coordinator', description: 'Organize group show attendance with want-list assignments, live floor check-ins, vendor ratings, and haul sharing.', tier: 'Industry-First', category: 'Social', status: 'live', path: '/card-show-squad', icon: 'MapPin', phase: 275, keywords: ['card show', 'squad', 'vendor', 'floor', 'haul', 'check-in', 'booth', 'convention'] },
  { id: 'group-buy-coop', name: 'Group Buy & Wholesale Co-op', description: 'Pool capital for case and lot purchases at wholesale pricing with ownership splits — cooperative bulk purchasing, not breaks.', tier: 'Industry-First', category: 'Social', status: 'live', path: '/group-buy-coop', icon: 'ShoppingCart', phase: 276, keywords: ['group buy', 'wholesale', 'co-op', 'bulk', 'case', 'cooperative', 'capital', 'pool'] },
  { id: 'draft-night-war-room', name: 'Draft Night War Room', description: 'Synchronized draft watch parties with real-time card price tracking, group prediction markets, and live position-taking.', tier: 'Industry-First', category: 'Social', status: 'live', path: '/draft-night-war-room', icon: 'Radio', phase: 277, keywords: ['draft', 'war room', 'watch party', 'prediction', 'live', 'NFL', 'NBA', 'MLB'] },
  { id: 'mentorship-exchange', name: 'Mentorship & Knowledge Exchange', description: 'Expert-to-novice pairing with guided collecting paths, skill progression trees, AMA scheduling, and structured learning.', tier: 'Industry-First', category: 'Social', status: 'live', path: '/mentorship-exchange', icon: 'GraduationCap', phase: 278, keywords: ['mentor', 'mentorship', 'knowledge', 'learning', 'skill', 'expert', 'novice', 'path'] },
  { id: 'dispute-arbitration', name: 'Community Dispute Arbitration', description: 'Peer-driven arbitration for trade disputes with evidence submission, reputation stakes, and binding resolution.', tier: 'Industry-First', category: 'Social', status: 'live', path: '/dispute-arbitration', icon: 'Scale', phase: 279, keywords: ['dispute', 'arbitration', 'resolution', 'evidence', 'trade', 'conflict', 'peer', 'panel'] },
  { id: 'group-insurance', name: 'Group Insurance & Risk Pool', description: 'Shared insurance premiums for high-value collections with pooled coverage dropping per-card cost 40-60%.', tier: 'Industry-First', category: 'Social', status: 'live', path: '/group-insurance', icon: 'ShieldCheck', phase: 280, keywords: ['insurance', 'risk pool', 'coverage', 'premium', 'theft', 'damage', 'claims', 'group'] },
  { id: 'crowd-pricing', name: 'Crowd-Sourced Price Discovery', description: 'Community pricing for illiquid cards with no comps — voting, confidence scoring, and expert-weighted consensus.', tier: 'Industry-First', category: 'Social', status: 'live', path: '/crowd-pricing', icon: 'Users', phase: 281, keywords: ['crowd', 'pricing', 'discovery', 'illiquid', 'consensus', 'vote', 'estimate', 'comp'] },
  { id: 'group-vault', name: 'Group Vault & Shared Storage', description: 'Co-located physical storage vaults with fractional access control, shared security costs, and climate monitoring.', tier: 'Industry-First', category: 'Social', status: 'live', path: '/group-vault', icon: 'Lock', phase: 282, keywords: ['vault', 'storage', 'shared', 'climate', 'security', 'safe', 'deposit', 'access'] },
  { id: 'swap-meet', name: 'Swap Meet & Trade Night Engine', description: 'Scheduled virtual trade events with auto-matching algorithms, live deal rooms, and post-event analytics.', tier: 'Industry-First', category: 'Social', status: 'live', path: '/swap-meet', icon: 'Repeat', phase: 283, keywords: ['swap', 'meet', 'trade night', 'virtual', 'matching', 'deal', 'event', 'exchange'] },
  // ─── v5.1+: PRD 4.11 — Next set of features not in the industry (Frontier) ───
  { id: 'agent-outcome-memory', name: 'Agent Outcome Memory Dashboard', description: 'Closed-loop view: recommendation → intent → outcome. What the AI recommended vs what you did vs what actually happened.', tier: 'Industry-First', category: 'AI', status: 'live', path: '/agent-outcome-memory', icon: 'Brain', phase: 264, keywords: ['agent', 'outcome', 'memory', 'recommendation', 'intent', 'fill', 'feedback'] },
  { id: 'market-truth-ledger', name: 'Market Truth Ledger', description: 'Single source of truth for what actually sold (eBay, auctions) with provenance. Normalized, queryable real sales per card.', tier: 'Industry-First', category: 'Data', status: 'live', path: '/market-truth-ledger', icon: 'BookOpen', phase: 265, keywords: ['market', 'truth', 'ledger', 'sold', 'comps', 'provenance'] },
  { id: 'counterparty-passport', name: 'Counterparty Passport', description: 'Portable reputation: trust score, dispute history, deal velocity across venues. Full passport with cross-platform identity.', tier: 'Industry-First', category: 'Trust', status: 'live', path: '/counterparty-passport', icon: 'Fingerprint', phase: 266, keywords: ['counterparty', 'passport', 'trust', 'reputation', 'cross-venue'] },
  { id: 'thesis-backtester', name: 'Thesis Backtester', description: 'If you had bought every card the agents recommended — hypothetical P&L. Proves or disproves agent value with outcome data.', tier: 'Industry-First', category: 'Analytics', status: 'live', path: '/thesis-backtester', icon: 'FlaskConical', phase: 267, keywords: ['thesis', 'backtester', 'agent', 'pnl', 'hypothetical'] },
  { id: 'liquidity-horizon', name: 'Liquidity Horizon Curve', description: 'Probability of exit at X% of FMV within 1d/7d/30d/90d. Institutional-style liquidity risk.', tier: 'Industry-First', category: 'Analytics', status: 'live', path: '/liquidity-horizon', icon: 'Clock', phase: 268, keywords: ['liquidity', 'horizon', 'exit', 'probability', 'fmv'] },
  { id: 'fv-confidence', name: 'Fair Value Confidence Interval', description: 'FMV as interval, not point — e.g. $500 (70%: $380–$620). Transparent uncertainty on every valuation.', tier: 'Industry-First', category: 'Analytics', status: 'live', path: '/fv-confidence', icon: 'BarChart3', phase: 269, keywords: ['fair value', 'confidence', 'interval', 'uncertainty', 'valuation'] },
  { id: 'regulatory-alerts', name: 'Regulatory Change Alerts', description: 'Proactive alerts when state/federal rules change: sales tax nexus, 1099-K, collectibles-as-securities.', tier: 'Industry-First', category: 'Risk', status: 'live', path: '/regulatory-alerts', icon: 'Shield', phase: 270, keywords: ['regulatory', 'alerts', 'tax', 'nexus', '1099-K', 'compliance'] },
  { id: 'agent-delegation-audit', name: 'Agent Delegation Audit', description: 'Full log of agent requested X → human approved/rejected → outcome Z with export for compliance.', tier: 'Industry-First', category: 'Risk', status: 'live', path: '/agent-delegation-audit', icon: 'FileCheck', phase: 271, keywords: ['agent', 'delegation', 'audit', 'compliance', 'log'] },
  { id: 'capital-flow-radar', name: 'Capital Flow Radar', description: 'Where is money moving? Players, grades, venues. Institutional-style flow analytics for the hobby.', tier: 'Industry-First', category: 'Analytics', status: 'live', path: '/capital-flow-radar', icon: 'Radar', phase: 272, keywords: ['capital', 'flow', 'radar', 'institutional', 'movement'] },
  { id: 'synthetic-index-builder', name: 'Synthetic Index Builder', description: 'User-defined custom index (e.g. PSA 10 Rookie QBs 2018–2022) with daily value and attribution.', tier: 'Industry-First', category: 'Portfolio', status: 'live', path: '/synthetic-index-builder', icon: 'BarChart3', phase: 273, keywords: ['synthetic', 'index', 'builder', 'custom', 'constituents'] },
  { id: 'catastrophe-liquidation', name: 'Catastrophe Liquidation Simulator', description: 'If you had to raise $X in 48 hours — optimal sequence and expected haircut. Emergency cash stress-test.', tier: 'Industry-First', category: 'Risk', status: 'live', path: '/catastrophe-liquidation', icon: 'AlertTriangle', phase: 274, keywords: ['catastrophe', 'liquidation', 'emergency', 'stress', '48h'] },
  { id: 'portfolio-immunization', name: 'Portfolio Immunization', description: 'Bond-style duration to a hobby recession. Rebalancing to shorten duration; convexity for collectibles.', tier: 'Industry-First', category: 'Portfolio', status: 'live', path: '/portfolio-immunization', icon: 'Shield', phase: 275, keywords: ['portfolio', 'immunization', 'duration', 'recession', 'convexity'] },
  { id: 'identity-graph', name: 'Cross-Venue Identity Graph', description: 'Link same seller/buyer across eBay, COMC, PWCC for true counterparty history and concentration risk.', tier: 'Industry-First', category: 'Trust', status: 'live', path: '/identity-graph', icon: 'Network', phase: 276, keywords: ['identity', 'graph', 'cross-venue', 'counterparty', 'link'] },
  { id: 'narrative-lifecycle', name: 'Narrative Lifecycle Tracker', description: 'Track narrative from first mention → social spike → price move → exhaustion. Time entries and exits.', tier: 'Industry-First', category: 'Analytics', status: 'live', path: '/narrative-lifecycle', icon: 'Radio', phase: 277, keywords: ['narrative', 'lifecycle', 'stages', 'exhaustion', 'timing'] },
  { id: 'agent-personality', name: 'Agent Personality Cloning', description: 'Train a mini-me agent (risk, league, max position) that screens and ranks opportunities; human still approves.', tier: 'Industry-First', category: 'AI', status: 'live', path: '/agent-personality', icon: 'Bot', phase: 278, keywords: ['agent', 'personality', 'clone', 'mini-me', 'risk', 'preference'] },

  // ─── v5.2 Frontier — industry-absent feature routes ────────────────────────
  { id: 'bid-ask-spread-predictor', name: 'Bid-Ask Spread Predictor', description: 'Predict bid-ask spread dynamics for cards and lots.', tier: 'Industry-First', category: 'Trading', status: 'live', path: '/bid-ask-spread-predictor', icon: 'TrendingUp', phase: 279, keywords: ['bid', 'ask', 'spread', 'liquidity'] },
  { id: 'wash-sale-horizon', name: 'Wash-Sale Horizon Calendar', description: 'Calendar and horizon tracking for wash-sale rules and tax-loss harvesting.', tier: 'Industry-First', category: 'Finance', status: 'live', path: '/wash-sale-horizon', icon: 'Calendar', phase: 280, keywords: ['wash sale', 'tax', 'horizon', 'harvesting'] },
  { id: 'seller-urgency-score', name: 'Seller Urgency Score', description: 'Score seller urgency from listing and behavior signals.', tier: 'Industry-First', category: 'Trading', status: 'live', path: '/seller-urgency-score', icon: 'Gauge', phase: 281, keywords: ['seller', 'urgency', 'negotiation'] },
  { id: 'portfolio-beta-index', name: 'Portfolio Beta to Index', description: 'Portfolio beta and correlation to custom or market indices.', tier: 'Industry-First', category: 'Portfolio', status: 'live', path: '/portfolio-beta-index', icon: 'BarChart3', phase: 282, keywords: ['beta', 'index', 'correlation', 'portfolio'] },
  { id: 'grading-queue-estimator', name: 'Grading Queue Estimator', description: 'Estimate grading queue wait times and turnaround by submitter and tier.', tier: 'Industry-First', category: 'Tools', status: 'live', path: '/grading-queue-estimator', icon: 'Clock', phase: 283, keywords: ['grading', 'queue', 'turnaround', 'PSA', 'BGS'] },
  { id: 'reputation-decay-tracker', name: 'Reputation Decay Tracker', description: 'Track reputation decay and recovery for counterparties and venues.', tier: 'Industry-First', category: 'Trust', status: 'live', path: '/reputation-decay-tracker', icon: 'TrendingDown', phase: 284, keywords: ['reputation', 'decay', 'trust'] },
  { id: 'event-impact-attribution', name: 'Event Impact Attribution', description: 'Attribute price and volume impact to events (games, news, releases).', tier: 'Industry-First', category: 'Analytics', status: 'live', path: '/event-impact-attribution', icon: 'Zap', phase: 285, keywords: ['event', 'impact', 'attribution', 'catalyst'] },
  { id: 'liquidity-reserve-calculator', name: 'Liquidity Reserve Calculator', description: 'Calculate recommended liquidity reserves for portfolios.', tier: 'Industry-First', category: 'Portfolio', status: 'live', path: '/liquidity-reserve-calculator', icon: 'Droplets', phase: 286, keywords: ['liquidity', 'reserve', 'cash', 'buffer'] },
  { id: 'cross-sport-momentum', name: 'Cross-Sport Momentum', description: 'Cross-sport momentum and spillover effects across leagues.', tier: 'Industry-First', category: 'Analytics', status: 'live', path: '/cross-sport-momentum', icon: 'Activity', phase: 287, keywords: ['cross-sport', 'momentum', 'spillover'] },
  { id: 'agent-confidence-history', name: 'Agent Confidence History', description: 'Historical view of agent confidence and calibration over time.', tier: 'Industry-First', category: 'AI', status: 'live', path: '/agent-confidence-history', icon: 'Brain', phase: 288, keywords: ['agent', 'confidence', 'calibration', 'history'] },
];

/** Core + every App.tsx route has a matching catalog row with id + status (see featureCatalogRouteSupplement). */
export const FEATURE_CATALOG: Feature[] = [
  ...FEATURE_CATALOG_CORE,
  ...FEATURE_CATALOG_ROUTE_SUPPLEMENT,
];

/** Tier display order and color configuration */
export const TIER_CONFIG: Record<FeatureTier, { order: number; color: string; bgColor: string; borderColor: string; label: string }> = {
  'Core': { order: 1, color: 'text-slate-300', bgColor: 'bg-slate-700/50', borderColor: 'border-slate-600', label: 'Core Platform' },
  'Competitive Moat': { order: 2, color: 'text-blue-400', bgColor: 'bg-blue-500/10', borderColor: 'border-blue-500/30', label: 'Competitive Moat' },
  'Bloomberg-Grade': { order: 3, color: 'text-purple-400', bgColor: 'bg-purple-500/10', borderColor: 'border-purple-500/30', label: 'Bloomberg-Grade' },
  'Advanced Intelligence': { order: 4, color: 'text-amber-400', bgColor: 'bg-amber-500/10', borderColor: 'border-amber-500/30', label: 'Advanced Intelligence' },
  'Differentiated': { order: 5, color: 'text-brand-lime', bgColor: 'bg-brand-lime/10', borderColor: 'border-brand-lime/30', label: 'Differentiated' },
  'Industry-First': { order: 6, color: 'text-red-400', bgColor: 'bg-red-500/10', borderColor: 'border-red-500/30', label: 'Industry-First' },
};

const searchableFeatureIds = new Set<string>(SEARCHABLE_FEATURE_IDS);
const featuredFeatureIds = new Set<string>(FEATURED_FEATURE_IDS);
const betaSurfaceEnabled =
  typeof import.meta !== 'undefined' &&
  (import.meta.env.VITE_FF_ENABLE_BETA_SURFACES === 'true' ||
    import.meta.env.VITE_FF_ENABLE_BETA_SURFACES === '1');
const demoSurfaceEnabled =
  typeof import.meta !== 'undefined' &&
  (import.meta.env.VITE_FF_ENABLE_DEMO_SURFACES === 'true' ||
    import.meta.env.VITE_FF_ENABLE_DEMO_SURFACES === '1');

function isDiscoverable(feature: Feature): boolean {
  if (!searchableFeatureIds.has(feature.id)) return false;
  if (!betaSurfaceEnabled && feature.status === 'beta') return false;
  if (!demoSurfaceEnabled && feature.status === 'demo') return false;
  return true;
}

export const DISCOVERABLE_FEATURE_CATALOG: Feature[] = FEATURE_CATALOG.filter(feature =>
  isDiscoverable(feature)
);

export const FEATURED_FEATURE_CATALOG: Feature[] = FEATURE_CATALOG.filter(feature =>
  featuredFeatureIds.has(feature.id) && isDiscoverable(feature)
);

/** Get all unique categories */
export function getCategories(features: Feature[] = DISCOVERABLE_FEATURE_CATALOG): string[] {
  const cats = new Set(features.map(f => f.category));
  return Array.from(cats).sort();
}

/** Search features by query string */
export function searchFeatures(query: string, features: Feature[] = DISCOVERABLE_FEATURE_CATALOG): Feature[] {
  if (!query.trim()) return [];
  const q = query.toLowerCase().trim();
  return features.filter(f =>
    f.name.toLowerCase().includes(q) ||
    f.description.toLowerCase().includes(q) ||
    f.keywords.some(kw => kw.includes(q)) ||
    f.category.toLowerCase().includes(q) ||
    f.tier.toLowerCase().includes(q)
  );
}

/** Group features by tier, sorted by tier order */
export function groupByTier(features: Feature[]): [FeatureTier, Feature[]][] {
  const groups = new Map<FeatureTier, Feature[]>();
  features.forEach(f => {
    const list = groups.get(f.tier) || [];
    list.push(f);
    groups.set(f.tier, list);
  });
  return Array.from(groups.entries()).sort((a, b) =>
    TIER_CONFIG[a[0]].order - TIER_CONFIG[b[0]].order
  );
}
