import type { CardInventory, Sport } from '../../types';

export const INSURANCE_REPLACEMENT_MULTIPLIER = 1.15;

export const INSURANCE_METHODOLOGY_BULLETS = [
  'Fair Market Value (FMV) is the card’s last recorded MSI current value, falling back to purchase price when no mark-to-market exists.',
  'Each line is timestamped with the valuation-as-of date (valuation timestamp, last valuation date, or report generation time).',
  `Replacement cost applies a ${Math.round((INSURANCE_REPLACEMENT_MULTIPLIER - 1) * 100)}% heuristic premium to FMV for like-kind replacement friction — not a carrier schedule.`,
  'Valuation sources are disclosed per line (eBay adapter, heuristic, or recorded inventory). This is not a USPAP appraisal.',
] as const;

export const INSURANCE_DISCLAIMER =
  'This packet is generated by Modern Sports Intelligence for collector records. Values are estimated Fair Market Value at generation time from inventory marks and optional market adapters. It does not constitute a licensed appraisal, proof of ownership, or a binding insurance schedule. Confirm figures with a certified appraiser and your carrier before filing a claim.';

export interface InsurancePacketLine {
  cardId: string;
  player: string;
  year: number;
  set: string;
  manufacturer: string;
  cardNumber: string;
  sport: Sport;
  condition: string;
  isGraded: boolean;
  gradingCompany?: string;
  grade?: string;
  certNumber?: string;
  fmv: number;
  fmvAsOf: string;
  valuationSource: string;
  replacementCost: number;
}

export interface InsurancePacketTotals {
  itemCount: number;
  totalFmv: number;
  totalReplacement: number;
  gradedCount: number;
  rawCount: number;
  certifiedCount: number;
}

export interface InsurancePacket {
  reportId: string;
  generatedAt: string;
  ownerName: string;
  policyNumber: string;
  items: InsurancePacketLine[];
  totals: InsurancePacketTotals;
  methodology: readonly string[];
  disclaimer: string;
}

export interface BuildInsurancePacketOptions {
  ownerName?: string;
  policyNumber?: string;
  generatedAt?: string;
  reportId?: string;
  includeSold?: boolean;
}

function roundCents(value: number): number {
  return Math.round(value * 100) / 100;
}

function resolveFmv(card: CardInventory): number {
  return roundCents(card.currentValue ?? card.purchasePrice ?? 0);
}

export function resolveFmvAsOf(card: CardInventory, generatedAt: string): string {
  return card.valuationTimestamp || card.lastValuationDate || generatedAt;
}

export function resolveValuationSourceLabel(card: CardInventory): string {
  switch (card.valuationSource) {
    case 'ebay-api':
      return 'eBay adapter';
    case 'historical-comps':
      return 'Historical comps';
    case 'gemini':
      return 'Gemini estimate';
    case 'fallback':
      return 'MSI fallback mark';
    default:
      return 'Inventory mark';
  }
}

export function buildInsurancePacket(
  inventory: CardInventory[],
  options: BuildInsurancePacketOptions = {}
): InsurancePacket {
  const generatedAt = options.generatedAt ?? new Date().toISOString();
  const includeSold = options.includeSold === true;
  const active = includeSold ? [...inventory] : inventory.filter((c) => c.status !== 'sold');

  const items: InsurancePacketLine[] = active
    .map((card) => {
      const fmv = resolveFmv(card);
      return {
        cardId: card.id,
        player: card.player,
        year: card.year,
        set: card.set,
        manufacturer: card.manufacturer,
        cardNumber: card.cardNumber,
        sport: card.sport,
        condition: card.condition,
        isGraded: card.isGraded,
        gradingCompany: card.gradingCompany,
        grade: card.grade,
        certNumber: card.certNumber,
        fmv,
        fmvAsOf: resolveFmvAsOf(card, generatedAt),
        valuationSource: resolveValuationSourceLabel(card),
        replacementCost: roundCents(fmv * INSURANCE_REPLACEMENT_MULTIPLIER),
      };
    })
    .sort((a, b) => b.fmv - a.fmv);

  const totalFmv = roundCents(items.reduce((sum, item) => sum + item.fmv, 0));
  const totalReplacement = roundCents(items.reduce((sum, item) => sum + item.replacementCost, 0));
  const gradedCount = items.filter((item) => item.isGraded).length;

  return {
    reportId: options.reportId ?? `INS-${Date.now().toString(36).toUpperCase()}`,
    generatedAt,
    ownerName: options.ownerName?.trim() || 'Collector',
    policyNumber: options.policyNumber?.trim() || '',
    items,
    totals: {
      itemCount: items.length,
      totalFmv,
      totalReplacement,
      gradedCount,
      rawCount: items.length - gradedCount,
      certifiedCount: items.filter((item) => !!item.certNumber).length,
    },
    methodology: INSURANCE_METHODOLOGY_BULLETS,
    disclaimer: INSURANCE_DISCLAIMER,
  };
}
