export const PRIMARY_NAV_IDS = [
  'dashboard',
  'collection',
  'builder',
  'deepsearch',
  'audit',
  'mlbstats',
  'prospects',
  'favorites',
  'players',
  'teams',
  'games',
  'trends',
  'compare',
  'alerts',
  'warroom',
  'guilds',
  'leaderboard',
  'features',
  'liquidity-twin',
  'counterparty-trust-graph',
  'portfolio-scenario-theater',
  'private-deal-room-agent',
  'catalyst-market',
  'api-licensing',
  'card-show-mode',
  'collection-narrative',
  'frontier-lab',
  'billing',
  'settings',
] as const;

/** Dealer / floor loop: book → inventory → scan/price → terminal → account. */
export const MOBILE_NAV_IDS = [
  'dashboard',
  'collection',
  'card-show-mode',
  'warroom',
  'settings',
] as const;

export const FEATURED_FEATURE_IDS = [
  'dashboard',
  'collection',
  'deep-search',
  'war-room',
  'catalyst-market',
  'collector-audit-dossier',
  'api-licensing',
  'provenance-chain',
  'portfolio-audit',
  'liquidity-twin',
  'private-deal-room-agent',
  'portfolio-scenario-theater',
] as const;

export const SEARCHABLE_FEATURE_IDS = [
  'dashboard',
  'collection',
  'deep-search',
  'auth-system',
  'billing',
  'mlb-stats',
  'players',
  'watchlist',
  'portfolio-audit',
  'teams',
  'games',
  'trends',
  'compare',
  'war-room',
  'multi-agent',
  'morning-briefing',
  'provenance-chain',
  'api-licensing',
  'card-show-mode',
  'portfolio-builder',
  'prospect-pipeline',
  'notification-center',
  'benchmarking',
  'collector-audit-dossier',
  'liquidity-twin',
  'private-deal-room-agent',
  'counterparty-trust-graph',
  'catalyst-market',
  'portfolio-scenario-theater',
  'frontier-lab',
  'restoration-risk-ledger',
  'claims-recovery-studio',
  'venue-failure-drill',
  'opportunity-crowding-index',
  'provenance-gap-heatmap',
  'museum-loan-desk',
  'counterfeit-cluster-radar',
  'capital-stack-optimizer',
  'prestige-spillover-engine',
  'reacquisition-radar',
  'public-portfolio',
  'collection-share',
  'analytics-reports',
  'data-import',
  'insurance-report',
  'insurance-manager',
  'fiscal-intel',
  'price-history',
  'command-palette',
  'bulk-operations',
  'market-ticker',
  'usability',
  'card-genome-sequencer',
  'injury-oracle',
  'cross-asset-correlation-v2',
  'collector-social-graph',
  'restoration-simulator',
  'market-maker-arena',
  'portfolio-stress-tester',
  'rookie-pipeline-scanner',
  'forensics-lab',
  'card-decay-predictor',
  'narrative-arc-engine',
  'liquidity-depth-scanner',
  'contagion-mapper',
  'grail-index-constructor',
  'print-run-decoder',
  'temporal-arbitrage-radar',
  'collection-dna-mixer',
  'card-yield-farming',
  'chaos-theory-simulator',
  'dopamine-cycle-tracker',
  'hobby-liquidity-crisis',
  'memory-index',
  'pop-forecaster',
  'draft-capital-futures',
  'shadow-inventory',
  'emotion-journal',
  'estate-succession',
  'refractor-mapper',
  'centering-analyzer',
  'what-if-simulator',
  'grading-batch-planner',
  'ebay-listing-generator',
  'wax-break-roi-tracker',
  'regulatory-compliance-radar',
  'acoustic-authentication',
  'dealer-flow-intelligence',
  'psychographic-demand',
  'micro-geographic-demand',
  'cross-hobby-contagion',
  'venue-health-oracle',
  'negotiation-replay',
  'card-material-spectrometry',
  'generational-demand-forecaster',
  // v7.1: Industry-Absent Innovation — Round 4 (Phases 234-253)
  'slab-case-forensics',
  'grading-arbitrage',
  'influencer-quantifier',
  'card-dna-fingerprint',
  'sentiment-half-life',
  'break-even-countdown',
  'collector-burnout-index',
  'flip-streak-analytics',
  'market-momentum-lines',
  'hobby-entry-ramp',
  'async-auction-negotiation',
  'portfolio-stress-test',
  'phenome-pipeline',
  'card-aging-simulator',
  'mystery-sniper-detector',
  'narrative-premium-index',
  'edition-print-run',
  'error-variety-hunter',
  'cross-platform-arbitrage',
  'auto-buy-rule-engine',
  'auction-equilibrium',
  'memetic-propagation',
  'agent-outcome-memory',
  'market-truth-ledger',
  'counterparty-passport',
  'thesis-backtester',
  'liquidity-horizon',
  'fv-confidence',
  'regulatory-alerts',
  'agent-delegation-audit',
  'capital-flow-radar',
  'synthetic-index-builder',
  'catastrophe-liquidation',
  'portfolio-immunization',
  'identity-graph',
  'narrative-lifecycle',
  'agent-personality',
  'circadian-optimizer',
  'cultural-velocity',
  'counterparty-fingerprint',
  'collection-topology',
  'survivorship-bias',
  'forgery-evolution',
  'decision-fatigue',
  'opportunity-cost-phantom',
  'shared-watchlists',
  'group-breaks',
  'club-management',
  'collective-grading',
  'shared-dashboards',
  'rbac-teams',
  'white-label-api',
  'dealer-inventory',
  'fund-reporting',
  'audit-trail',
  'collaborative-set-registry',
  'card-show-squad',
  'group-buy-coop',
  'draft-night-war-room',
  'mentorship-exchange',
  'dispute-arbitration',
  'group-insurance',
  'crowd-pricing',
  'group-vault',
  'swap-meet',
  'bid-ask-spread-predictor',
  'wash-sale-horizon',
  'seller-urgency-score',
  'portfolio-beta-index',
  'grading-queue-estimator',
  'reputation-decay-tracker',
  'event-impact-attribution',
  'liquidity-reserve-calculator',
  'cross-sport-momentum',
  'agent-confidence-history',
] as const;

export const COMMAND_ROUTES = [
  {
    id: 'nav-dashboard',
    label: 'Go to Dashboard',
    description: 'Portfolio command center and live metrics',
    path: '/',
    keywords: ['home', 'overview', 'portfolio'],
  },
  {
    id: 'nav-collection',
    label: 'Go to Collection',
    description: 'Manage inventory, grading, and dossier workflows',
    path: '/collection',
    keywords: ['cards', 'inventory', 'assets'],
  },
  {
    id: 'nav-prospects',
    label: 'Go to Prospects',
    description: 'Track breakout signals and pipeline momentum',
    path: '/prospects',
    keywords: ['milb', 'minor league'],
  },
  {
    id: 'nav-alerts',
    label: 'Go to Alerts',
    description: 'Review notifications and portfolio triggers',
    path: '/alerts',
    keywords: ['notifications', 'inbox'],
  },
  {
    id: 'nav-mlb-stats',
    label: 'Go to PressBox Hub',
    description: 'Live MLB data, player lookup, and performance context',
    path: '/mlb-stats',
    keywords: ['mlb', 'stats', 'baseball'],
  },
  {
    id: 'nav-audit',
    label: 'Go to Portfolio Audit',
    description: 'Benchmark risk, returns, and diversification',
    path: '/audit',
    keywords: ['report', 'analysis', 'risk'],
  },
  {
    id: 'nav-search',
    label: 'Go to Deep Search',
    description: 'Run semantic search across comparable assets',
    path: '/deep-search',
    keywords: ['find', 'lookup', 'semantic'],
  },
  {
    id: 'nav-settings',
    label: 'Go to Settings',
    description: 'Manage account, notifications, and sharing',
    path: '/settings',
    keywords: ['profile', 'preferences', 'account'],
  },
  {
    id: 'nav-dossier',
    label: 'Go to Audit Dossier',
    description: 'Open the collector operating record export workflow',
    path: '/audit-dossier',
    keywords: ['audit', 'dossier', 'insurance', 'tax'],
  },
  {
    id: 'nav-audit-trail',
    label: 'Go to Audit Trail',
    description: 'Compliance log, recorded events, and retention policies',
    path: '/audit-trail',
    keywords: ['audit', 'compliance', 'trail', 'log', 'security', 'recorded'],
  },
  {
    id: 'nav-war-room',
    label: 'Go to Analyst War Room',
    description: 'Multi-agent terminal for Alpha-grade portfolio decisions',
    path: '/war-room',
    keywords: ['war room', 'terminal', 'agents', 'bloomberg'],
  },
  {
    id: 'nav-catalyst',
    label: 'Go to Catalyst Market',
    description: 'Holdings-linked event-driven repricing windows',
    path: '/catalyst-market',
    keywords: ['catalyst', 'news', 'events', 'holdings'],
  },
  {
    id: 'nav-api',
    label: 'Go to API & Licensing',
    description: 'Production data API catalog and Alpha licensing desk',
    path: '/api-licensing',
    keywords: ['api', 'developer', 'licensing', 'keys'],
  },
  {
    id: 'nav-card-show',
    label: 'Go to Card Show Mode',
    description: 'Dealer floor scan → price → inventory loop',
    path: '/card-show-mode',
    // Avoid bare "scan" — that keyword owns the /scan Alpha slash command.
    keywords: ['show', 'dealer', 'floor', 'booth', 'mobile', 'field'],
  },
] as const;
